(() => {
  "use strict";

  const exercise = (id, title, file, difficulty, prompt, contract, topics, hints) => ({
    id,
    title,
    file,
    difficulty,
    prompt,
    contract,
    topics,
    hints,
  });

  const step = (title, body) => ({ title, body });

  window.COURSE_DATA = {
    title: "Python Foundations Playground",
    note: "The repository contains solutions but not the original statements. Every question below is a teaching prompt inferred from its filename, inputs, function signature, and observed behaviour.",
    chapters: [
      {
        id: "py01",
        number: "01",
        title: "First Programs",
        folder: "Py01 First Programs",
        summary: "Learn the smallest complete Python programs: values, variables, keyboard input, arithmetic, and printed output.",
        topics: ["print", "variables", "input", "arithmetic"],
        runbook: [
          step("Read the data flow", "Underline each input, follow every assignment from top to bottom, and state what must be printed."),
          step("Choose a tiny example", "Use small numbers you can calculate by hand before running the program."),
          step("Trace types and units", "Write the type and real-world unit beside each variable, especially hours versus minutes."),
          step("Run and compare", "Execute the script, compare its output with your hand calculation, then try one boundary case."),
        ],
        exercises: [
          exercise(
            "py01-first-programs",
            "First Programs",
            "Py01 First Programs/First Programs.py",
            1,
            "Write the smallest Python program that prints the greeting “Hello world!” exactly once.",
            "Script → stdout: Hello world!",
            ["print", "string literals"],
            [
              "Python sends text to standard output with the built-in print function.",
              "Put the exact greeting inside quotes; punctuation and capitalization are part of the expected output.",
            ],
          ),
          exercise(
            "py01-fixme",
            "FIXME",
            "Py01 First Programs/FIXME.py",
            1,
            "Build “Hello world!” from two variables: start with “Hello”, append the remaining text, and print the result.",
            "Script with no input → stdout: Hello world!",
            ["variables", "string concatenation"],
            [
              "Store the first word in one variable rather than printing it immediately.",
              "The + operator joins strings; remember that the space and exclamation mark must be included.",
            ],
          ),
          exercise(
            "py01-diagram",
            "Diagram",
            "Py01 First Programs/Diagram.py",
            1,
            "Read two integers a and b, then print the result of subtracting 5 from a and adding twice b.",
            "stdin: a, b (integers) → stdout: a - 5 + 2 × b",
            ["input", "operator precedence"],
            [
              "Convert each input string to an integer before calculating.",
              "Multiplication is evaluated before addition and subtraction; add parentheses if they make the intention clearer.",
            ],
          ),
          exercise(
            "py01-avoid-sums",
            "Avoid Sums",
            "Py01 First Programs/Avoid sums.py",
            2,
            "Read two integers and print their sum while avoiding the binary + operator.",
            "stdin: a, b (integers) → stdout: a + b",
            ["unary operators", "arithmetic"],
            [
              "Adding a value is equivalent to subtracting its opposite.",
              "Apply unary minus to b, then subtract that result from a.",
              "Check with both a positive and a negative second input.",
            ],
          ),
          exercise(
            "py01-uncensor",
            "Uncensor",
            "Py01 First Programs/Uncensor.py",
            1,
            "Read two integers, add them, multiply the sum by the constant 10, and print the result.",
            "stdin: a, b (integers) → stdout: 10 × (a + b)",
            ["constants", "arithmetic"],
            [
              "Keep the fixed multiplier in a clearly named variable.",
              "Use parentheses so the addition happens before multiplication.",
            ],
          ),
          exercise(
            "py01-travelling",
            "Travelling",
            "Py01 First Programs/Travelling.py",
            2,
            "Given travel time as whole hours and minutes, calculate the rounded average speed needed to cover 313 km.",
            "stdin: hours, minutes → stdout: round(313 ÷ total_hours)",
            ["unit conversion", "division", "rounding"],
            [
              "Convert minutes to a fraction of an hour before combining the two inputs.",
              "Average speed is distance divided by elapsed time.",
              "Test 3 hours 0 minutes: your result should be close to 104 km/h.",
            ],
          ),
        ],
      },
      {
        id: "py08",
        number: "08",
        title: "Recursion",
        folder: "Py08 Recursion",
        summary: "Solve a problem through smaller versions of itself using explicit base cases, guaranteed progress, structural traversal, and combinatorial search.",
        topics: ["recursion", "base cases", "call trees", "decomposition"],
        runbook: [
          step("Write the base case", "Name the smallest valid input and return its answer directly before thinking about the recursive branch."),
          step("Prove progress", "Point to the argument that becomes smaller or structurally simpler on every recursive call."),
          step("Trace the call tree", "Expand a tiny example by hand until every branch reaches a base case, then combine returns upward."),
          step("Check cost and depth", "Look for repeated calls, factorial branching, missing memoization, and inputs large enough to exceed Python’s recursion limit."),
        ],
        exercises: [
          exercise(
            "py08-sum-digits",
            "Sum of Digits",
            "Py08 Recursion/Sum of digits.py",
            2,
            "Return the sum of a non-negative integer’s decimal digits using recursion.",
            "sum_digits_rec(n) → integer digit sum",
            ["base case", "digit decomposition"],
            [
              "A one-digit number is its own digit sum.",
              "Separate one digit and recurse on the remaining digits.",
              "Add the separated digit only when the recursive result returns.",
            ],
          ),
          exercise(
            "py08-gcd",
            "Greatest Common Divisor",
            "Py08 Recursion/Greatest common divisor.py",
            2,
            "Compute the greatest common divisor recursively with Euclid’s remainder algorithm.",
            "gcd_rec(n1, n2) → gcd; n2 must be non-zero initially",
            ["Euclidean algorithm", "remainder", "tail recursion"],
            [
              "Compute the remainder n1 % n2.",
              "A zero remainder makes n2 the answer.",
              "Otherwise recurse with n2 as the first argument and the remainder as the second.",
            ],
          ),
          exercise(
            "py08-find-treasure",
            "Find the Treasure",
            "Py08 Recursion/Find the treasure.py",
            2,
            "Starting at a coordinate, recursively apply a list of up, down, left, and right steps and return the final coordinate.",
            "find_treasure(pos, steps) → final (x, y)",
            ["head/tail recursion", "tuple state"],
            [
              "An empty steps list is the base case: return the current position.",
              "Apply only steps[0] to produce the next position.",
              "Recurse with that new position and steps[1:].",
            ],
          ),
          exercise(
            "py08-juggler",
            "Juggler Sequence",
            "Py08 Recursion/Juggler Sequence.py",
            3,
            "Return term p of the Juggler sequence starting at n: an even term becomes floor(√n), while an odd term becomes floor(n^(3/2)).",
            "juggler(n, p) → integer; p=0 returns n",
            ["recursive sequence", "parity", "powers"],
            [
              "Position zero is the starting value and forms the base case.",
              "Calculate the previous term once, then inspect its parity.",
              "Avoid calling the same recursive subproblem several times; store its result locally.",
            ],
          ),
          exercise(
            "py08-biggest-member",
            "Biggest Member",
            "Py08 Recursion/Biggest Member.py",
            3,
            "Search a recursively nested tuple and return the tuple with the greatest direct length, keeping the outer candidate when lengths tie.",
            "biggest_member(atuple) → tuple",
            ["structural recursion", "nested tuples", "maximum tracking"],
            [
              "Treat the current tuple as the first best candidate.",
              "Recurse only into children that are tuples.",
              "Replace the candidate only when a recursive result is strictly longer.",
            ],
          ),
          exercise(
            "py08-digits-average",
            "Digits Average",
            "Py08 Recursion/Digits average.py",
            4,
            "Recursively replace adjacent decimal digit pairs with their ceiling averages until one digit remains.",
            "digits_average(n) → one-digit integer; helper builds each shorter number",
            ["helper recursion", "digit arithmetic", "reduction"],
            [
              "Separate the problem into building one shorter number and repeating whole passes.",
              "When building a pass, combine the last two digits, then recurse after removing the last digit.",
              "Once the shorter number is complete, call the top-level reduction again until n < 10.",
            ],
          ),
          exercise(
            "py08-no-pairs-of-ones",
            "No Pairs of 1s",
            "Py08 Recursion/No pairs of 1s.py",
            4,
            "Count the binary strings of length k that contain no consecutive 1s, using the Fibonacci recurrence.",
            "no_consecutives1(k) → fib(k + 2)",
            ["combinatorial recurrence", "Fibonacci", "binary strings"],
            [
              "Partition valid strings by whether their final digit is 0 or 1.",
              "A valid string ending in 1 must have 0 immediately before it.",
              "The two smaller counts form the Fibonacci recurrence; determine the +2 index shift from k = 0 and k = 1.",
            ],
          ),
          exercise(
            "py08-preorder",
            "Preorder",
            "Py08 Recursion/Preorder.py",
            4,
            "Flatten a nested tuple representation of a tree in preorder, returning encountered values and ignoring None placeholders.",
            "preorder(tree) → flat list",
            ["tree traversal", "structural recursion", "list concatenation"],
            [
              "None contributes an empty list and an ordinary value contributes a one-item list.",
              "When the current item is nested, recursively traverse it before the remaining siblings.",
              "Combine partial traversals in root/left/right order rather than sorting them.",
            ],
          ),
          exercise(
            "py08-last-man-standing",
            "Last Man Standing",
            "Py08 Recursion/Last Man Standing.py",
            4,
            "Solve the Josephus elimination problem recursively: remove every step-th item around the circle until one survivor remains.",
            "last_man_standing(alist, step) → surviving element",
            ["recursive elimination", "rotation", "modulo"],
            [
              "One remaining item is the base case.",
              "Rotate the current list so the item to eliminate is at the front.",
              "Remove that item and recurse on a list whose length is one smaller.",
            ],
          ),
          exercise(
            "py08-unordered-permutations",
            "Unordered Permutations",
            "Py08 Recursion/Unordered permutations.py",
            5,
            "Return the set of all unique permutations of a tuple using recursive choice and combination.",
            "permutations(atuple) → set of tuples",
            ["backtracking", "tuple slicing", "sets"],
            [
              "Choose each element in turn as the first element of a result.",
              "Recursively permute the tuple with that chosen position removed.",
              "Prefix the chosen element to every smaller permutation and add results to a set to remove duplicates.",
            ],
          ),
          exercise(
            "py08-knapsack",
            "Knapsack",
            "Py08 Recursion/Knapsack.py",
            5,
            "Choose available wishlist units that fit a budget, exploring take/skip choices recursively, and return selected quantities by product.",
            "knapsack(money, products, wishlist) → purchased counts. The repository notes that its current implementation fails private tests, so use it as a debugging exercise rather than a verified answer.",
            ["combinatorial search", "budget constraint", "solution reconstruction"],
            [
              "Expand each requested quantity into an individual candidate item, or recurse directly over product/count state.",
              "At each item, compare skipping it with taking it when its price is affordable.",
              "Define the objective clearly—usually minimum remaining budget without going negative—then reconstruct counts from the best feasible choice.",
            ],
          ),
        ],
      },
      {
        id: "py09",
        number: "09",
        title: "FP with Collections",
        folder: "Py09 FP with collections",
        summary: "Describe collection work as a pipeline of selection, transformation, combination, and lazy production using functional tools.",
        topics: ["map", "filter", "reduce", "generators"],
        runbook: [
          step("Name the pipeline", "Write the stages as input → filter → map → reduce or yield before expressing them in code."),
          step("Define one-value callbacks", "Make each lambda or function answer one focused question for one item."),
          step("Keep stages pure", "Avoid append or other hidden mutation inside map and filter; let each stage return its own value."),
          step("Inspect laziness", "Materialize map/filter only when the contract asks for a list, and consume generators a few values at a time."),
        ],
        exercises: [
          exercise(
            "py09-fahrenheit",
            "Fahrenheit",
            "Py09 FP with collections/Fahrenheit.py",
            1,
            "Convert a collection of Celsius temperatures to Fahrenheit with map, rounding every result to two decimals.",
            "to_fahrenheit(t) → list; formula: c × 9/5 + 32",
            ["map", "lambda", "temperature conversion"],
            [
              "Write and verify the conversion for one temperature first.",
              "Pass that one-value transformation to map.",
              "map is lazy in Python 3, so convert it to a list for this contract.",
            ],
          ),
          exercise(
            "py09-celsius",
            "Celsius",
            "Py09 FP with collections/Celsius.py",
            1,
            "Convert a collection of Fahrenheit temperatures to Celsius with map, rounding every result to one decimal.",
            "to_celsius(t) → list; formula: (f - 32) × 5/9",
            ["map", "lambda", "rounding"],
            [
              "Subtract 32 before multiplying by 5/9.",
              "Use a lambda that receives one Fahrenheit value.",
              "Materialize the mapped iterator as a list.",
            ],
          ),
          exercise(
            "py09-polynomials",
            "Polynomials",
            "Py09 FP with collections/Polynomials.py",
            2,
            "Evaluate a polynomial whose coefficient at index i multiplies x^i, using enumerate, map, and sum.",
            "evaluate(a, x) → Σ coefficient[i] × x^i",
            ["enumerate", "map", "sum"],
            [
              "Pair every coefficient with its zero-based index.",
              "Transform each (index, coefficient) pair into coefficient × x**index.",
              "Sum the transformed terms to produce the polynomial value.",
            ],
          ),
          exercise(
            "py09-rearranging",
            "Rearranging",
            "Py09 FP with collections/Rearranging.py",
            2,
            "Stably place all values ≤ 0 before all values > 0 using filter.",
            "rearrange(l) → new list preserving order within both groups",
            ["filter", "stable partition", "predicates"],
            [
              "Filter the original sequence once for non-positive values.",
              "Filter it again with the complementary positive predicate.",
              "Concatenate the two materialized groups in the requested order.",
            ],
          ),
          exercise(
            "py09-map-filter-reduce",
            "Map, Filter & Reduce",
            "Py09 FP with collections/Map Filter & Reduce.py",
            3,
            "Filter lst with f1, transform the survivors with f2, then combine them with reducer f3.",
            "map_filter_reduce(lst, f1, f2, f3) → one reduced value; assumes at least one item survives",
            ["functional composition", "filter", "map", "reduce"],
            [
              "Pipeline order matters: rejected values should never be transformed.",
              "Feed filter(f1, lst) directly into map(f2, ...).",
              "Import reduce from functools and apply f3 only at the final stage.",
            ],
          ),
          exercise(
            "py09-interval-generator",
            "Generator from an Interval List",
            "Py09 FP with collections/Generator from an interval list.py",
            3,
            "Lazily yield every integer from each inclusive (start, end) interval, preserving interval order, overlaps, and duplicates.",
            "generator(intlist) → iterator of integers",
            ["yield", "ranges", "lazy evaluation"],
            [
              "Process one interval at a time rather than constructing every expanded list first.",
              "range excludes its stop, so use end + 1 for an inclusive interval.",
              "yield each integer directly from the nested loop.",
            ],
          ),
        ],
      },
      {
        id: "py10",
        number: "10",
        title: "Effect-Free Programming",
        folder: "Py10 Effect-free programming",
        summary: "Prefer predictable transformations that do not change their inputs, using comprehensions, generators, closures, and local state.",
        topics: ["purity", "comprehensions", "closures", "lazy evaluation"],
        runbook: [
          step("Declare effects", "State whether the function mutates input, prints, reads, or depends on external state; aim for none unless required."),
          step("Build new values", "Use comprehensions or pure helpers to create results instead of editing caller-owned collections."),
          step("Separate eager and lazy", "Return a list when all values are needed now and yield when callers should consume them incrementally."),
          step("Check repeatability", "Call the function twice with the same input and confirm equal output plus unchanged input data."),
        ],
        exercises: [
          exercise(
            "py10-fahrenheit",
            "Fahrenheit",
            "Py10 Effect-free programming/Fahrenheit.py",
            1,
            "Convert Celsius values to Fahrenheit with a list comprehension and no input mutation, rounding to two decimals.",
            "to_fahrenheit(t) → new list; c × 9/5 + 32",
            ["list comprehension", "pure mapping"],
            [
              "Put the one-value formula before the for clause.",
              "Iterate directly over the input values and round each new result.",
            ],
          ),
          exercise(
            "py10-celsius",
            "Celsius",
            "Py10 Effect-free programming/Celsius.py",
            1,
            "Convert Fahrenheit values to Celsius with a list comprehension and no input mutation, rounding to one decimal.",
            "to_celsius(t) → new list; (f - 32) × 5/9",
            ["list comprehension", "temperature conversion"],
            [
              "Apply the subtraction before the scale factor.",
              "Let the comprehension create a new list rather than changing t.",
            ],
          ),
          exercise(
            "py10-polynomials",
            "Polynomials",
            "Py10 Effect-free programming/Polynomials.py",
            2,
            "Evaluate ascending-order polynomial coefficients at x with enumerate, a comprehension, and sum.",
            "evaluate(a, x) → Σ a[i] × x^i",
            ["comprehension", "enumerate", "sum"],
            [
              "enumerate supplies each exponent and coefficient together.",
              "Create the coefficient × x**exponent terms inside a comprehension, then sum them.",
            ],
          ),
          exercise(
            "py10-rearranging",
            "Rearranging",
            "Py10 Effect-free programming/Rearranging.py",
            2,
            "Stably place non-positive values before positive values with comprehensions, leaving the source untouched.",
            "rearrange(l) → new partitioned list",
            ["conditional comprehension", "stable partition", "purity"],
            [
              "Build one new list for x <= 0 and another for x > 0.",
              "Concatenate them; comprehension traversal naturally preserves order within each group.",
            ],
          ),
          exercise(
            "py10-composites",
            "Composites",
            "Py10 Effect-free programming/Composites.py",
            3,
            "Lazily yield every composite integer from 4 through n.",
            "get_composites(n) → iterator of composite integers",
            ["generator", "divisibility", "early exit"],
            [
              "A composite has at least one divisor strictly between 1 and itself.",
              "Search candidate divisors and yield the number at the first exact division.",
              "Break after yielding so each composite appears only once.",
            ],
          ),
          exercise(
            "py10-batch-normalization",
            "Median Batch Normalization",
            "Py10 Effect-free programming/Median Batch Normalization.py",
            4,
            "Split a list into batches, subtract each batch’s median from every member, and lazily yield the normalized batches; a one-item batch becomes [0].",
            "batch_norm(alist, batch_size) → iterator of new lists",
            ["chunking", "median", "generator", "pure transformation"],
            [
              "Slice the current batch and use its actual length, especially for the final partial batch.",
              "Sort a copy; choose the middle value for odd length or average the middle pair for even length.",
              "Yield a new list of value - median without changing the source batch.",
            ],
          ),
          exercise(
            "py10-shortening-numbers",
            "Shortening Numbers",
            "Py10 Effect-free programming/Shortening Numbers.py",
            4,
            "Return a formatter closure that abbreviates numeric strings using the largest applicable power of base and the corresponding supplied suffix; stringify unsupported inputs unchanged.",
            "shorten(suffixes, base) → compute(value) → string",
            ["closures", "validation", "magnitude formatting"],
            [
              "The outer function captures suffixes and base, then returns an inner compute function.",
              "Inside compute, reject non-string or non-numeric input by returning its string representation.",
              "Search powers from largest to smallest; integer-divide at the first match and append the matching suffix. Handle zero explicitly.",
            ],
          ),
        ],
      },
      {
        id: "py11",
        number: "11",
        title: "Divide and Conquer",
        folder: "Py11 Divide and Conquer",
        summary: "Use structural promises—sorted, monotone, or bitonic—to locate boundaries and peaks efficiently, alongside a sorting baseline.",
        topics: ["sorting", "binary search", "invariants", "complexity"],
        runbook: [
          step("State the structure", "Record whether the input is arbitrary, sorted, monotone, or bitonic; the algorithm depends on that promise."),
          step("Choose the comparison", "Identify the midpoint observation that safely discards half of the remaining search interval."),
          step("Maintain boundaries", "Give low and high exact meanings, update one on every iteration, and write a termination condition that cannot stall."),
          step("Prove with edges", "Test the smallest valid list, a transition near each edge, a central transition, and the expected time complexity."),
        ],
        exercises: [
          exercise(
            "py11-bubble-sort",
            "Bubble Sort",
            "Py11 Divide and Conquer/Bubble Sort.py",
            2,
            "Sort a list in ascending order with bubble sort, repeating passes until one complete pass makes no swaps.",
            "bubble_sort(alist) → the same list sorted in place",
            ["sorting", "adjacent swap", "convergence flag"],
            [
              "Compare every neighbouring pair in a pass.",
              "Swap when the left value is greater and remember that the pass changed something.",
              "Stop only when a full pass leaves the list untouched; optionally shorten later passes because the largest values settle at the end.",
            ],
          ),
          exercise(
            "py11-count-zeros",
            "Find the Number of Zeros",
            "Py11 Divide and Conquer/Find the number of zeros.py",
            4,
            "A callback returns a monotone list of one or more 1s followed by 0s. Find the number of zeros by locating the first zero with binary search.",
            "count_zeros(f) → zero count; f() supplies the list",
            ["binary search", "transition point", "logarithmic complexity"],
            [
              "Once you know the first zero’s index, the answer is len(values) - index.",
              "When values[mid] is zero, keep mid as a candidate and search further left.",
              "When it is one, discard mid and everything left of it; define behavior for an all-ones or all-zeros input.",
            ],
          ),
          exercise(
            "py11-bitonic-point",
            "Find the Bitonic Point",
            "Py11 Divide and Conquer/Find the bitonic point.py",
            4,
            "A callback returns a sequence that strictly rises and then falls. Find and return its peak value in logarithmic time.",
            "bitonic_point(f) → peak value; f() supplies the sequence",
            ["bitonic sequence", "binary search", "peak finding"],
            [
              "Compare values[mid] with values[mid + 1] to determine the local slope.",
              "An upward slope puts the peak to the right; a downward slope keeps mid or the left half.",
              "Stop when low == high and return values[low], taking care that mid + 1 stays in range.",
            ],
          ),
        ],
      },
      {
        id: "py05",
        number: "05",
        title: "Strings & Tuples",
        folder: "Py05 Strings & Tuples",
        summary: "Work with immutable sequences through indexing, slicing, splitting, joining, classification, and nested tuple traversal.",
        topics: ["strings", "tuples", "slicing", "sequence traversal"],
        runbook: [
          step("Sketch the indexes", "Write the sequence with zero-based indexes, including negative indexes when slicing from the end."),
          step("Preserve immutability", "Build a new string or tuple instead of trying to change an existing immutable value in place."),
          step("Separate parsing from logic", "Split text into meaningful pieces first, transform those pieces, then join only at the output boundary."),
          step("Check awkward shapes", "Test empty text, one item, even and odd lengths, repeated values, and one nested tuple."),
        ],
        exercises: [
          exercise(
            "py05-counting-characters",
            "Counting Characters",
            "Py05 Strings & Tuples/Counting Characters.py",
            1,
            "Count the letters, digits, and all other characters in a string and return those three counts as a tuple.",
            "count_chars(a_string) → (letter_count, digit_count, other_count)",
            ["character classification", "tuple return"],
            [
              "Keep three independent counters.",
              "Use isalpha first, isdigit second, and let the final else collect spaces and punctuation.",
            ],
          ),
          exercise(
            "py05-counting-elements",
            "Counting Elements",
            "Py05 Strings & Tuples/Counting elements.py",
            1,
            "Return the index of the first element in tup that is itself a tuple, or -1 if no nested tuple exists.",
            "count_until(tup) → zero-based index or -1",
            ["enumerate", "type inspection", "early return"],
            [
              "enumerate gives you each element and its index at the same time.",
              "Return immediately on the first tuple; only return -1 after the entire sequence has been checked.",
            ],
          ),
          exercise(
            "py05-discard-middle",
            "Discarding the Middle",
            "Py05 Strings & Tuples/Discarding the middle.py",
            1,
            "For strings longer than three characters, return the first two and last two characters; otherwise return an empty string.",
            "discard_middle(s) → shortened string or ''",
            ["slicing", "guard clause"],
            [
              "Handle the short-string rule before taking slices.",
              "s[:2] selects the first pair and s[-2:] selects the final pair.",
            ],
          ),
          exercise(
            "py05-longest-word",
            "Longest Word",
            "Py05 Strings & Tuples/Longest word.py",
            1,
            "Return the length of the longest whitespace-separated word in a non-empty string.",
            "longest(s) → integer length",
            ["split", "maximum tracking"],
            [
              "Split with no argument so runs of whitespace are handled naturally.",
              "Initialize the maximum from a real word, then update it only when a longer word appears.",
            ],
          ),
          exercise(
            "py05-first-repeating-letter",
            "First Repeating Letter",
            "Py05 Strings & Tuples/First repeating letter.py",
            2,
            "Scanning left to right, return the first character that appears again later in the string.",
            "repeated_letter(s) → character, or None when none repeats",
            ["slicing", "membership", "early return"],
            [
              "At each position, search only the suffix that comes after the current character.",
              "Return as soon as the current character is found in that remaining suffix.",
              "If the loop finishes naturally, Python returns None.",
            ],
          ),
          exercise(
            "py05-find-treasure",
            "Find the Treasure",
            "Py05 Strings & Tuples/Find the treasure.py",
            2,
            "Starting at coordinate (x, y), follow hyphen-separated up, down, left, and right steps and return the final coordinate.",
            "map(pos, steps) → (final_x, final_y)",
            ["split", "tuple state", "direction mapping"],
            [
              "Split the instruction string on '-' before processing it.",
              "Up/down change y; left/right change x.",
              "Tuples are immutable, so assign a new coordinate after each move.",
            ],
          ),
          exercise(
            "py05-remove-leading-zeros",
            "Remove Leading Zeros",
            "Py05 Strings & Tuples/Remove leading zeros.py",
            2,
            "Normalize a dot-separated IP-like address by removing leading zeros from each component while keeping an all-zero component as “0”.",
            "remove_leading(ip) → normalized dot-separated string",
            ["split/join", "nested traversal", "normalization"],
            [
              "Treat each dot-separated component independently.",
              "Find its first non-zero character; if none exists, preserve one final zero.",
              "Join all normalized components with dots only after processing them all.",
            ],
          ),
          exercise(
            "py05-summary-ranges",
            "Summary Ranges",
            "Py05 Strings & Tuples/Summary ranges.py",
            4,
            "Compress a comma-separated ascending list of integers so consecutive runs become start->end and isolated values remain unchanged.",
            "summary_ranges('1,2,3,5,7,8') → '1->3,5,7->8'",
            ["parsing", "run detection", "formatting"],
            [
              "Parse the comma-separated tokens and track the start and end of the current run.",
              "A run continues only when the next integer equals the current integer + 1.",
              "When a run ends, format one value for a singleton or start->end for a longer run.",
            ],
          ),
          exercise(
            "py05-palindrome-index",
            "Palindrome Index",
            "Py05 Strings & Tuples/Palindrome index.py",
            5,
            "Return the index of one character whose removal makes s a palindrome, or -1 when s already works or cannot be fixed with one removal.",
            "palindrome_index(s) → index or -1",
            ["two pointers", "candidate testing", "palindromes"],
            [
              "Compare characters from both ends until the first mismatch.",
              "Only two removals can fix that mismatch: remove the left character or remove the right character.",
              "Test each candidate by checking whether the remaining string equals its reverse; avoid modifying the same list for both tests.",
            ],
          ),
          exercise(
            "py05-greatest-member",
            "Greatest Member",
            "Py05 Strings & Tuples/Greatest Member.py",
            5,
            "Score strings by the sum of their character codes and nested tuples by the recursive sum of their members; return the highest-scoring top-level member.",
            "greatest_member(a_tuple) → top-level string/tuple, or () when every score is zero",
            ["nested tuples", "recursion", "scoring"],
            [
              "Create one helper that scores a string with ord for each character.",
              "Create another helper that recursively adds the scores inside a tuple.",
              "Compare the score of each top-level member, while returning the member itself rather than its numeric score.",
            ],
          ),
        ],
      },
      {
        id: "py06",
        number: "06",
        title: "Lists",
        folder: "Py06 Lists",
        summary: "Use mutable sequences deliberately: copy before destructive work, update by index, traverse nested lists, and model elimination or cancellation.",
        topics: ["lists", "mutation", "indexes", "nested data"],
        runbook: [
          step("Decide mutation policy", "Write down whether the function may modify its input; make a copy when callers should keep the original."),
          step("Track index movement", "After pop or insertion, re-evaluate the next index because every later element may have shifted."),
          step("Choose the right shape", "Use one list for output, a stack for cancellation, or a matrix-like nested list when rows and columns matter."),
          step("Test duplicates and sizes", "Include duplicate values, one-element lists, even/odd inner lengths, and a full wrap-around elimination."),
        ],
        exercises: [
          exercise(
            "py06-rotating",
            "Rotating",
            "Py06 Lists/Rotating.py",
            1,
            "Return a list rotated three positions to the left.",
            "rotate_list(l) → l[3:] + l[:3]",
            ["slicing", "concatenation"],
            [
              "A left rotation splits the list after the third item.",
              "Put the suffix before the first three elements without changing their internal order.",
            ],
          ),
          exercise(
            "py06-fibonacci",
            "Fibonacci Numbers",
            "Py06 Lists/Fibonacci numbers.py",
            2,
            "Return a list containing the first n Fibonacci numbers, beginning with 0, 1.",
            "fib(n) → list of length n; fib(1) == [0]",
            ["list growth", "recurrence"],
            [
              "Handle n = 1 before creating the usual two-value seed.",
              "Every later item is the sum of the previous two list entries.",
              "The range should add exactly enough values for the final list length to equal n.",
            ],
          ),
          exercise(
            "py06-fetch-middle",
            "Fetching the Middle",
            "Py06 Lists/Fetching the middle.py",
            2,
            "For each non-empty inner list, collect its middle value when its length is odd or the mean of its two middle values when even.",
            "fetch_middle(llists) → one result per inner list",
            ["nested lists", "indexes", "parity"],
            [
              "Integer division by 2 gives the middle index for an odd-length list.",
              "For an even length, the two middle positions are length // 2 - 1 and length // 2.",
              "Append exactly one result for every inner list.",
            ],
          ),
          exercise(
            "py06-bagdiff",
            "Bagdiff",
            "Py06 Lists/Bagdiff.py",
            3,
            "Compute bag difference: for each value in ys, remove one matching occurrence from xs if present, then return the remaining xs values.",
            "bagdiff(xs, ys) → list representing multiset xs − ys",
            ["multisets", "mutation", "duplicates"],
            [
              "Membership finds whether a value can be removed; index finds one occurrence.",
              "Do not remove items from the list you are currently iterating over, or elements can be skipped.",
              "Copy xs first if the function should not modify the caller’s list.",
            ],
          ),
          exercise(
            "py06-nth-lowest",
            "N-th Lowest",
            "Py06 Lists/N-th lowest.py",
            3,
            "Find the n-th smallest number by repeatedly locating and removing the current maximum instead of sorting the list.",
            "nth_lowest(lnum, n) → n-th smallest value (1-based n)",
            ["selection", "destructive algorithm", "loop invariant"],
            [
              "After removing the largest value, the desired rank among the remaining values is unchanged.",
              "Continue until only n - 1 smaller values sit below the last removed candidate.",
              "State whether duplicates count as separate positions and avoid overwriting the built-in max name.",
            ],
          ),
          exercise(
            "py06-orthogonal-matrices",
            "Orthogonal Matrices",
            "Py06 Lists/Orthogonal matrices.py",
            3,
            "Return whether a 2×2 matrix is orthogonal by checking that the matrix multiplied by its transpose equals the identity.",
            "is_orthogonal(mx) → bool for a 2×2 nested list",
            ["matrices", "transpose", "dot product"],
            [
              "Transpose swaps rows and columns.",
              "Each product cell is a row dot a column.",
              "For this exercise, compare the four calculated cells with [[1, 0], [0, 1]].",
            ],
          ),
          exercise(
            "py06-pattern-hunting",
            "Pattern Hunting",
            "Py06 Lists/Pattern hunting.py",
            4,
            "For two parallel string lists, collect the paired item from the other list whenever an item contains pattern p; return all collected values in descending order.",
            "pattern_hunting(l1, l2, p) → descending list of paired strings",
            ["parallel lists", "substring search", "sorting"],
            [
              "The same index links an item in l1 to its partner in l2.",
              "Run the rule in both directions: matches in l1 contribute l2 items and matches in l2 contribute l1 items.",
              "Use a focused helper for substring detection, then sort the complete result once.",
            ],
          ),
          exercise(
            "py06-minimizing-path",
            "Minimizing the Path",
            "Py06 Lists/Minimizing the path.py",
            4,
            "Simplify a path by repeatedly cancelling adjacent opposite moves: UP/DOWN and LEFT/RIGHT.",
            "min_path(path) → reduced direction list",
            ["stack", "cancellation", "adjacency"],
            [
              "A cancellation can expose a new opposite pair, so one simple left-to-right comparison is not enough.",
              "Use the result list as a stack: compare each new direction with its last item.",
              "Pop for an opposite pair; otherwise push the new direction.",
            ],
          ),
          exercise(
            "py06-last-man-standing",
            "Last Man Standing",
            "Py06 Lists/Last Man Standing.py",
            4,
            "Solve the Josephus problem iteratively: moving around a circular list, remove every step-th remaining person until one value survives.",
            "last_man_standing(a_list, step) → surviving element",
            ["circular indexing", "pop", "Josephus problem"],
            [
              "Modulo converts an ever-growing position into a valid circular index.",
              "After pop, the next item shifts into the removed index, so calculate the next start carefully.",
              "Trace a four-item example by hand and keep eliminating until len(list) == 1.",
            ],
          ),
        ],
      },
      {
        id: "py07",
        number: "07",
        title: "Dictionaries & Sets",
        folder: "Py07 Dictionaries & Sets",
        summary: "Model lookup, frequency, uniqueness, relationships, and aggregation with key/value mappings and set algebra.",
        topics: ["dictionaries", "sets", "aggregation", "lookup"],
        runbook: [
          step("Choose the key", "Identify the stable value used for lookup, grouping, or counting before building the dictionary."),
          step("Use set algebra deliberately", "Reach for union, intersection, and symmetric difference when membership matters more than order or duplicates."),
          step("Control mutation", "Copy mappings before deleting clues or entries unless consuming the caller’s data is an explicit part of the contract."),
          step("Verify ties and money", "Test duplicate values, equal frequencies, absent keys, exact budgets, and currency converted to integer cents."),
        ],
        exercises: [
          exercise(
            "py07-academy-awards",
            "Academy Awards",
            "Py07 Dictionaries & Sets/Academy Awards.py",
            1,
            "Given a list of award records, count how many awards belong to each record’s second value.",
            "academy_awards(alist) → {second_field: count}",
            ["frequency dictionary", "tuple unpacking"],
            [
              "Use the second item in each record as the dictionary key.",
              "Initialize an unseen key to 1 and increment an existing key.",
            ],
          ),
          exercise(
            "py07-lost-element",
            "Lost Element",
            "Py07 Dictionaries & Sets/Lost element.py",
            1,
            "Two sets differ by exactly one element. Return that element.",
            "lost_element(s1, s2) → the only value in the symmetric difference",
            ["sets", "symmetric difference"],
            [
              "The desired item belongs to one set but not both.",
              "Compute union minus intersection, or use the symmetric-difference operator directly.",
            ],
          ),
          exercise(
            "py07-most-frequent",
            "Most Frequent",
            "Py07 Dictionaries & Sets/Most frequent.py",
            2,
            "Return the most frequent list value; when several values tie, return the greatest of them.",
            "most_frequent(a_list) → value",
            ["frequency table", "tie breaking"],
            [
              "First build a value-to-count dictionary.",
              "Track all keys at the current maximum count, replacing that list when a larger count appears.",
              "Apply max to the tied keys only after the frequency scan is complete.",
            ],
          ),
          exercise(
            "py07-sort-by-value",
            "Sort by Value",
            "Py07 Dictionaries & Sets/Sort by value.py",
            3,
            "Return a dictionary’s (key, value) items ordered by ascending value, preserving every item even when values tie.",
            "sort_by_value(mapping) → list of (key, value) tuples",
            ["dictionary items", "sorting", "key functions"],
            [
              "Keep keys and values together rather than sorting the values alone.",
              "Pass a key function that extracts item[1] to sorted.",
              "Test two different keys with the same value to ensure neither disappears or repeats.",
            ],
          ),
          exercise(
            "py07-complete-pairs",
            "Pairs of Complete Strings",
            "Py07 Dictionaries & Sets/Pairs of complete strings.py",
            3,
            "Combine every string from s1 with every string from s2 and return the concatenations that contain all 26 distinct alphabet letters.",
            "complete_pairs(s1, s2) → set of complete concatenated strings",
            ["Cartesian product", "sets", "alphabet coverage"],
            [
              "Use nested loops to visit every cross-list pair.",
              "A set of the concatenated string removes duplicate characters.",
              "Compare against the alphabet itself when inputs may include nonletters; length 26 alone assumes only lowercase letters.",
            ],
          ),
          exercise(
            "py07-change",
            "Change",
            "Py07 Dictionaries & Sets/Change.py",
            3,
            "Break a euro amount into greedy counts of €2, €1, 50c, 20c, 10c, 5c, 2c, and 1c coins.",
            "change(money) → {denomination_in_euros: coin_count}",
            ["greedy method", "currency", "dictionary order"],
            [
              "Convert money to integer cents before repeatedly subtracting coins.",
              "Process denominations from largest to smallest.",
              "Include a zero count for denominations that are not used, and test an exact-cent value for floating-point drift.",
            ],
          ),
          exercise(
            "py07-treasure",
            "Treasure",
            "Py07 Dictionaries & Sets/Treasure.py",
            3,
            "Start at coordinate (0, 0), repeatedly follow coordinate-to-coordinate clues, and return the first coordinate that has no next clue.",
            "treasure(clues) → final coordinate",
            ["dictionary lookup", "state traversal", "cycle awareness"],
            [
              "The current coordinate is a key and its value is the next coordinate.",
              "Continue only while the current coordinate exists in the mapping.",
              "Track or remove visited clues to prevent a cycle from looping forever; copy the mapping if inputs must stay unchanged.",
            ],
          ),
          exercise(
            "py07-heroes-villains",
            "Heroes and Villains",
            "Py07 Dictionaries & Sets/Heroes and Villains.py",
            4,
            "Process heroes in order against a villain. Only matching categories fight; a strong-enough hero wins and gains one score, otherwise the villain loses half that hero’s health.",
            "fight(heroes, villain) → formatted hero-win or villain-win message",
            ["record dictionaries", "simulation", "state update"],
            [
              "Skip a hero whose category does not match the villain’s.",
              "Compare health before applying damage; return immediately if the hero can defeat the villain.",
              "After a failed attack, subtract half the hero’s health and round the villain’s health to one decimal place.",
            ],
          ),
          exercise(
            "py07-budgeting",
            "Budgeting",
            "Py07 Dictionaries & Sets/Budgeting.py",
            4,
            "Buy wishlist quantities within a budget while considering requested products from highest price to lowest, and return the quantities purchased.",
            "budgeting(budget, products, wishlist) → {product: purchased_quantity}",
            ["sorting mappings", "greedy allocation", "budget state"],
            [
              "Restrict the candidates to products that actually appear in the wishlist.",
              "Order candidates by products[name] descending before purchasing repeated units.",
              "Check affordability before subtracting; decide whether one unaffordable product should stop all work or simply be skipped.",
            ],
          ),
          exercise(
            "py07-tfidf",
            "TF-IDF",
            "Py07 Dictionaries & Sets/TF-IDF.py",
            5,
            "Build a lowercased word-to-document vector using raw term frequency × log(number of documents / document frequency), rounded to three decimals.",
            "tfidf(documents) → {word: [score_for_doc_0, score_for_doc_1, ...]}",
            ["nested aggregation", "TF-IDF", "logarithms"],
            [
              "First create a zero-filled vector for each new word and count occurrences in the current document position.",
              "Document frequency counts documents containing the word, not its total occurrences.",
              "After counts are complete, multiply each raw count by log(N / df) and round each vector value to three decimals.",
            ],
          ),
        ],
      },
      {
        id: "py02",
        number: "02",
        title: "Simple Data",
        folder: "Py02 Simple data",
        summary: "Turn simple numeric and textual inputs into useful results with formulas, integer division, remainders, formatting, and rounding.",
        topics: ["numbers", "formulas", "division", "formatting"],
        runbook: [
          step("Name inputs and units", "List each input, its Python type, and its unit before writing the formula."),
          step("Write the formula first", "Express the calculation on paper and identify where parentheses or powers are needed."),
          step("Check representation", "Choose // for whole groups, % for remainders, and round only at the requested output boundary."),
          step("Probe edge cases", "Try zero, exact multiples, day wrap-around, and values close to a rounding boundary."),
        ],
        exercises: [
          exercise(
            "py02-circle-area",
            "Circle Area",
            "Py02 Simple data/Circle Area.py",
            1,
            "Read a circle radius and print its area rounded to two decimal places, using 3.14159 for π.",
            "stdin: r (number) → stdout: round(3.14159 × r², 2)",
            ["powers", "rounding"],
            [
              "The area of a circle is πr².",
              "Python’s exponent operator is **, and round accepts the number of decimal places as its second argument.",
            ],
          ),
          exercise(
            "py02-hypotenuse",
            "Hypotenuse",
            "Py02 Simple data/Hypotenuse.py",
            1,
            "For a right isosceles triangle whose two legs both have length n, print the hypotenuse rounded to two decimals.",
            "stdin: n (integer) → stdout: round(√(2n²), 2)",
            ["Pythagorean theorem", "square root"],
            [
              "Apply a² + b² = c² with a = b = n.",
              "Import sqrt from math, or raise the sum to the power 0.5.",
            ],
          ),
          exercise(
            "py02-means",
            "Means",
            "Py02 Simple data/Means.py",
            1,
            "Read three integers and print their arithmetic mean rounded to two decimal places.",
            "stdin: n1, n2, n3 → stdout: round((n1 + n2 + n3) ÷ 3, 2)",
            ["average", "rounding"],
            [
              "An arithmetic mean is the sum of all observations divided by their count.",
              "Use parentheses around the sum before dividing by 3.",
            ],
          ),
          exercise(
            "py02-trip-cost",
            "Trip Cost",
            "Py02 Simple data/Trip Cost.py",
            2,
            "Calculate the fuel cost of a trip from its distance, litres consumed per 100 km, and price per litre; round to cents.",
            "stdin: distance_km, litres_per_100km, price_per_litre → stdout: trip cost",
            ["rates", "unit conversion", "rounding"],
            [
              "First determine how many 100 km blocks the trip contains.",
              "Multiply those blocks by litres per 100 km, then by price per litre.",
              "Keep full precision during the calculation and round the final amount only.",
            ],
          ),
          exercise(
            "py02-repetitions",
            "Repetitions",
            "Py02 Simple data/Repetitions.py",
            2,
            "Read some text and n, then print the text n times on one line with hyphens between copies and no trailing hyphen.",
            "stdin: text, n → stdout example for n=3: text-text-text",
            ["loops", "output formatting"],
            [
              "A separator belongs between items, so there are n - 1 separators.",
              "Either print the first n - 1 copies with end='-' or build the result with join.",
              "Check n = 1: the output should be just the original text.",
            ],
          ),
          exercise(
            "py02-easy-change",
            "Easy Change",
            "Py02 Simple data/Easy change.py",
            2,
            "Given an integer price and amount received, return change using 50, 20, 10, and 5-value notes from largest to smallest.",
            "stdin: price, received → stdout: counts of 50, 20, 10, and 5 notes",
            ["integer division", "remainder", "greedy method"],
            [
              "Start with change = received - price.",
              "For each note, // gives how many fit and % gives what remains.",
              "Process denominations from largest to smallest and hand the remainder to the next step.",
            ],
          ),
          exercise(
            "py02-alarm-clock",
            "Alarm Clock",
            "Py02 Simple data/Alarm clock.py",
            2,
            "Read a time in hours and minutes, add 6 hours 51 minutes, and print the resulting 24-hour time as HH:MM.",
            "stdin: hour, minute → stdout: zero-padded HH:MM after +06:51",
            ["time arithmetic", "formatting"],
            [
              "The result may cross midnight, so it must wrap after 23:59.",
              "You can convert everything to minutes and use modulo 24 × 60, or use datetime and timedelta.",
              "Format both components with two digits; 7:05 becomes 07:05.",
            ],
          ),
          exercise(
            "py02-quadratic-formula",
            "Quadratic Formula",
            "Py02 Simple data/Quadratic Formula.py",
            3,
            "Read coefficients a, b, and c of a quadratic equation and print its two real roots rounded to two decimals.",
            "stdin: a, b, c → stdout: (-b ± √(b² - 4ac)) ÷ 2a",
            ["formula translation", "square root", "rounding"],
            [
              "Calculate the discriminant b² - 4ac first and assume it is non-negative.",
              "The entire numerator must be divided by 2a; parentheses prevent precedence mistakes.",
              "Compute one root with +sqrt(discriminant) and the other with -sqrt(discriminant).",
            ],
          ),
          exercise(
            "py02-weird-sum",
            "Weird Sum",
            "Py02 Simple data/Weird Sum.py",
            3,
            "Read a and b. If their sum is even, print twice the sum; if it is odd, print the sum plus the product—without an explicit if statement.",
            "stdin: a, b → stdout: 2(a+b) when even, otherwise a+b+ab",
            ["parity", "boolean arithmetic"],
            [
              "For any integer s, s % 2 is 0 when s is even and 1 when it is odd.",
              "Build numeric selectors for the even and odd formulas, then add the selected results.",
              "Test one pair with an even sum and another with an odd sum.",
            ],
          ),
          exercise(
            "py02-multiples",
            "Multiples of 3 or 5",
            "Py02 Simple data/Multiples of 3 or 5.py",
            2,
            "Read n and print the sum of every integer from 0 through n that is divisible by 3 or by 5.",
            "stdin: n → stdout: Σ i for 0 ≤ i ≤ n where i % 3 = 0 or i % 5 = 0",
            ["loops", "divisibility", "accumulator"],
            [
              "Iterate through an inclusive range, which means the stop value must be n + 1.",
              "A number is divisible by d when number % d == 0.",
              "Use or, not two independent additions, so multiples of 15 are counted once.",
            ],
          ),
        ],
      },
      {
        id: "py03",
        number: "03",
        title: "Flow, Conditionals & Iteration",
        folder: "Py03 Flow, Condicionals & Iteration",
        summary: "Control what runs and how often: branch on conditions, maintain loop invariants, validate input, and build numeric algorithms.",
        topics: ["if/else", "for", "while", "accumulators"],
        runbook: [
          step("State the invariant", "Say what each loop variable means before, during, and after an iteration."),
          step("Dry-run a small case", "Make a table of variable values for two or three iterations, including the stopping condition."),
          step("Separate validation", "Reject impossible input before entering the main algorithm whenever the contract calls for it."),
          step("Test loop boundaries", "Check an empty or smallest range, one normal case, and a value that triggers every branch."),
        ],
        exercises: [
          exercise(
            "py03-who-needs-for",
            "Who Needs For",
            "Py03 Flow, Condicionals & Iteration/Who needs for.py",
            1,
            "Use a while loop to print the arithmetic sequence 4, 7, 10, …, 49, one value per line.",
            "Script with no input → stdout: values starting at 4, step 3, below 50",
            ["while loop", "counter"],
            [
              "Initialize the counter with the first value that must be printed.",
              "After printing, increase it by 3 and continue while it is below 50.",
            ],
          ),
          exercise(
            "py03-divisors",
            "Divisors",
            "Py03 Flow, Condicionals & Iteration/Divisors.py",
            2,
            "Read a positive integer n and print the sum of all its positive divisors, including 1 and n.",
            "stdin: n → stdout: sum(d for d in 1..n if n % d == 0)",
            ["divisibility", "accumulator"],
            [
              "No proper divisor other than n can be greater than n // 2.",
              "Accumulate divisors from 1 through n // 2, then add n once.",
              "Check a prime: its divisor sum should be 1 + n.",
            ],
          ),
          exercise(
            "py03-octal-to-decimal",
            "Octal to Decimal",
            "Py03 Flow, Condicionals & Iteration/Octal to Decimal.py",
            3,
            "Read a string of octal digits, reject any digit 8 or 9, otherwise convert the value to decimal without calling int(text, 8).",
            "stdin: octal text → stdout: decimal integer or “Not a valid number.”",
            ["positional notation", "validation", "loops"],
            [
              "In base 8, valid digits range from 0 to 7.",
              "A digit at distance p from the right contributes digit × 8ᵖ.",
              "Track the decreasing exponent as you scan left to right, or multiply an accumulator by 8 before adding each digit.",
            ],
          ),
          exercise(
            "py03-looping-numbers",
            "Looping Numbers",
            "Py03 Flow, Condicionals & Iteration/Looping Numbers.py",
            3,
            "Classify a digit string as a looping number when every adjacent pair moves by one digit forward (with 9→0 wrap) or one digit backward.",
            "stdin: digit string → stdout: “Looping number” or “Not a looping number”",
            ["adjacent pairs", "modulo", "flags"],
            [
              "Compare each digit with the digit immediately after it.",
              "Forward motion can be expressed as (current + 1) % 10; backward motion is current - 1.",
              "Start with a true flag and turn it false as soon as any pair violates both rules.",
            ],
          ),
          exercise(
            "py03-printing-pattern",
            "Printing a Pattern",
            "Py03 Flow, Condicionals & Iteration/Printing a Pattern.py",
            2,
            "Given n, print n rows: the first counts down from n to 1, and each next row starts one lower until the last row contains only 1.",
            "stdin: n → stdout example n=3: “3 2 1”, “2 1”, “1”",
            ["nested loops", "formatting"],
            [
              "The outer loop chooses the first number in each row.",
              "The inner loop prints from that row’s start down to 1.",
              "Print a newline only after the inner loop finishes.",
            ],
          ),
          exercise(
            "py03-prime-numbers",
            "Prime Numbers",
            "Py03 Flow, Condicionals & Iteration/Prime numbers.py",
            3,
            "Read lower and upper bounds and print all prime numbers in the inclusive interval.",
            "stdin: lower, upper → stdout: formatted list of primes between the bounds",
            ["nested loops", "prime test", "early exit"],
            [
              "A prime integer is at least 2 and has no divisor other than 1 and itself.",
              "For each candidate, test possible divisors and stop at the first exact division.",
              "It is sufficient to test through √candidate; also make sure 0 and 1 are not reported as prime.",
            ],
          ),
          exercise(
            "py03-combinations",
            "Combinations",
            "Py03 Flow, Condicionals & Iteration/Combinations.py",
            3,
            "Implement factorial iteratively, then use it to calculate the binomial coefficient C(n, r).",
            "factorial(n) → n!; C(n, r) → n! ÷ (r!(n-r)!)",
            ["functions", "factorial", "combinatorics"],
            [
              "The neutral value for repeated multiplication is 1.",
              "Multiply every integer from 1 through n to compute n!; 0! should remain 1.",
              "Use integer arithmetic for the final coefficient because the result is integral when 0 ≤ r ≤ n.",
            ],
          ),
          exercise(
            "py03-flow-diagram",
            "Flow Diagram",
            "Py03 Flow, Condicionals & Iteration/Flow diagram.py",
            4,
            "Translate a subtraction-based flow diagram into code that prints the greatest common divisor of two positive integers.",
            "stdin: two positive integers → stdout: gcd",
            ["Euclidean algorithm", "while loops", "state swaps"],
            [
              "Keep the larger value in R and the smaller in S before subtracting.",
              "Repeatedly subtract S from R until the remainder is no longer larger than S.",
              "When the remainder is non-zero, rotate the roles; when it reaches zero, S is the gcd.",
            ],
          ),
          exercise(
            "py03-grading-fp",
            "Grading FP",
            "Py03 Flow, Condicionals & Iteration/Grading FP.py",
            3,
            "Read LE, RE, PE, and TE grades. Reject values outside 0–100, print RFF if PE or TE is below 40, otherwise print the rounded weighted final grade.",
            "final = round((LE + RE + 13×PE + 5×TE) ÷ 100)",
            ["validation", "branch ordering", "weighted average"],
            [
              "Validate all four values before checking pass/fail rules.",
              "The practical and theoretical exams are gates: either below 40 produces RFF.",
              "Only calculate the weighted result after the input and gate checks pass.",
            ],
          ),
          exercise(
            "py03-pi",
            "π",
            "Py03 Flow, Condicionals & Iteration/π.py",
            4,
            "Approximate π to eight decimal places with 51 terms of Ramanujan’s 1/π series.",
            "Script with no input → stdout: π rounded to 8 decimal places",
            ["series", "factorial", "numerical methods"],
            [
              "Accumulate the term containing (4k)!, k!⁴, 1103 + 26390k, and 396⁴ᵏ for k from 0 through 50.",
              "Multiply the sum by 2√2 / 9801 to obtain an approximation of 1/π.",
              "Invert that result only after the series has been accumulated, then round the final π value.",
            ],
          ),
        ],
      },
      {
        id: "py04",
        number: "04",
        title: "Functions",
        folder: "Py04 Functions",
        summary: "Package algorithms into reusable contracts with parameters, return values, helper functions, validation, and decomposition.",
        topics: ["functions", "parameters", "return values", "helpers"],
        runbook: [
          step("Write the contract", "State accepted inputs, returned value, formatting, and invalid-input behaviour before coding."),
          step("Choose helpers", "Give one focused responsibility to each helper and avoid mixing calculation with printing."),
          step("Check every path", "Make sure each branch returns the correct type and that a valid value cannot fall through accidentally."),
          step("Call with examples", "Test the smallest input, a normal input, and one value for each special case in the contract."),
        ],
        exercises: [
          exercise(
            "py04-boolean-function",
            "Boolean Function",
            "Py04 Functions/Boolean Function.py",
            2,
            "Implement validate(grade) so it returns True only for an int or float between 0 and 100 inclusive, and False for every other value.",
            "validate(grade) → bool",
            ["type checking", "boolean expressions", "validation"],
            [
              "Both a range condition and a numeric-type condition must be true.",
              "Remember that bool is a subclass of int; exact type checks exclude True and False if the contract requires it.",
              "Guard comparisons that might raise when grade is a string or another incompatible type.",
            ],
          ),
          exercise(
            "py04-counting-characters",
            "Counting Characters",
            "Py04 Functions/Counting Characters.py",
            1,
            "Return how many times char occurs in word, or -1 when it does not occur.",
            "count_chars(word, char) → positive count or -1",
            ["iteration", "counter", "sentinel value"],
            [
              "Start the count at zero and inspect every character in the word.",
              "After the loop, translate a zero count into the required sentinel value -1.",
            ],
          ),
          exercise(
            "py04-dogs-age",
            "Dog’s Age in Dog’s Years",
            "Py04 Functions/Dog's age in dog's years.py",
            2,
            "Convert a dog’s human age: each of the first two years counts as 10.5 dog years and each later year counts as 4.",
            "dogs(h_age) → dog age as a number",
            ["piecewise function", "conditionals"],
            [
              "The formula changes after the first two human years.",
              "For ages above 2, start with 21 and add 4 for every remaining year.",
            ],
          ),
          exercise(
            "py04-greatest-number",
            "The Greatest Number",
            "Py04 Functions/The greatest number.py",
            2,
            "Rearrange the decimal digits of a non-negative integer to form the greatest possible integer.",
            "greatest(num) → integer with the same digits in descending order",
            ["string conversion", "sorting"],
            [
              "Converting the number to text makes each digit directly iterable.",
              "Sort the characters in descending order, join them, then convert the result back to int.",
            ],
          ),
          exercise(
            "py04-ugly-number",
            "Ugly Number",
            "Py04 Functions/Ugly number.py",
            3,
            "Return whether n is an ugly number: a positive integer whose only prime factors are 2, 3, and 5.",
            "ugly(n) → bool",
            ["factorization", "while loops"],
            [
              "Repeatedly divide out every factor of 2, then 3, then 5.",
              "If nothing except those factors remains, the reduced value will be 1.",
              "Test values with repeated factors, such as 60, and a forbidden factor, such as 14.",
            ],
          ),
          exercise(
            "py04-collatz",
            "The Collatz Sequence",
            "Py04 Functions/The Collatz sequence.py",
            3,
            "Return the Collatz sequence from positive n down to 1 as comma-separated text with no spaces.",
            "collatz(n) → string such as “6,3,10,5,16,8,4,2,1”",
            ["looping state", "parity", "string building"],
            [
              "Begin the output with n itself.",
              "For an even value divide by 2; for an odd value replace it with 3n + 1.",
              "Append each new value and stop only after 1 has been included.",
            ],
          ),
          exercise(
            "py04-pascal",
            "Pascal’s Triangle",
            "Py04 Functions/Pascal's triangle.py",
            3,
            "Return the first n rows of Pascal’s triangle as text, with spaces between values and a newline after each row.",
            "pascal(n) → multiline string of binomial coefficients",
            ["nested loops", "binomial coefficients", "formatting"],
            [
              "Row i contains i + 1 values for positions j = 0 through i.",
              "Each value can be calculated as i! / (j!(i-j)!).",
              "Build one row at a time, remove its trailing space, then append a newline.",
            ],
          ),
          exercise(
            "py04-get-positions",
            "Get Positions",
            "Py04 Functions/Get positions.py",
            3,
            "Translate words in a sentence into their zero-based positions in word_list and return those positions separated by spaces; return an empty string when the expected mapping cannot be completed.",
            "get_positions(sentence, word_list) → position string or ''",
            ["tokenization", "lookup", "output contract"],
            [
              "Split the sentence into whole words before looking anything up.",
              "For each word, search word_list and append the first matching index.",
              "Decide explicitly what to do when a sentence word is missing; keep the return format consistent with the exercise contract.",
            ],
          ),
          exercise(
            "py04-digits-average",
            "Digits Average",
            "Py04 Functions/Digits average.py",
            4,
            "Repeatedly replace each adjacent digit pair with the ceiling of its average until only one digit remains, then return it.",
            "digits_average(n) → one-digit integer",
            ["digit extraction", "iteration", "recursion"],
            [
              "One pass over a k-digit number produces a new number with k - 1 digits.",
              "Extract neighbouring digits with % 10 and // 10, using ceil for each average.",
              "Feed the newly built number back into the same process until it is below 10.",
            ],
          ),
          exercise(
            "py04-caesar-fibonacci",
            "Caesar Cipher with Fibonacci",
            "Py04 Functions/Caesar cipher with Fib.py",
            5,
            "Encrypt an uppercase message by shifting each alphabetic character backward by the Fibonacci number for its zero-based position; preserve non-letters.",
            "caesar(message) → transformed string; shift(character, number) handles A–Z wrap",
            ["character codes", "modulo", "Fibonacci", "decomposition"],
            [
              "Keep a position counter even when the current character is not a letter.",
              "Convert A–Z to a 0–25 offset, subtract the shift, apply modulo 26, and convert back.",
              "Use a helper for the character shift and compute the Fibonacci amount separately for each position.",
            ],
          ),
        ],
      },
    ],
  };

  window.COURSE_DATA.chapters.sort((left, right) => left.number.localeCompare(right.number));
})();
