(() => {
  "use strict";

  const section = (
    title,
    explanation,
    exampleCode,
    checklist,
    takeaway,
    commonPitfall,
  ) => ({
    title,
    explanation,
    exampleCode,
    checklist,
    takeaway,
    commonPitfall,
  });

  const runStep = (phase, action, evidence, why, whenStuck) => ({
    phase,
    action,
    evidence,
    why,
    whenStuck,
  });

  window.LEARNING_CONTENT = {
    meta: {
      totalExercises: 92,
      maxStars: 239,
      starRule: "A passed exercise awards the number of stars shown by its difficulty.",
    },

    ranks: [
      {
        level: 1,
        name: "PEP Explorer",
        minStars: 0,
        minExercises: 0,
        description: "You are learning to read Python as a precise set of instructions.",
        accent: "#8b95a7",
      },
      {
        level: 2,
        name: "Indent Apprentice",
        minStars: 8,
        minExercises: 3,
        description: "Your first programs run, and indentation is becoming a useful tool rather than a surprise.",
        accent: "#3ccf91",
      },
      {
        level: 3,
        name: "Loop Tamer",
        minStars: 27,
        minExercises: 10,
        description: "You can control repetition, trace state, and stop loops deliberately.",
        accent: "#35b8ff",
      },
      {
        level: 4,
        name: "Function Forger",
        minStars: 55,
        minExercises: 22,
        description: "You shape small contracts into reusable functions with dependable return values.",
        accent: "#7c8cff",
      },
      {
        level: 5,
        name: "Collection Alchemist",
        minStars: 91,
        minExercises: 36,
        description: "Strings, lists, tuples, dictionaries, and sets transform cleanly in your hands.",
        accent: "#a77bff",
      },
      {
        level: 6,
        name: "Recursion Ranger",
        minStars: 132,
        minExercises: 52,
        description: "You can navigate nested structures and prove that recursive calls make progress.",
        accent: "#e06cff",
      },
      {
        level: 7,
        name: "Algorithm Architect",
        minStars: 181,
        minExercises: 72,
        description: "You choose representations, invariants, and complexity with intention.",
        accent: "#ff8a65",
      },
      {
        level: 8,
        name: "Pythonic Grandmaster",
        minStars: 239,
        minExercises: 92,
        description: "Every challenge is green; your solutions are clear, tested, and recognizably Pythonic.",
        accent: "#ffd166",
      },
    ],

    badges: [
      {
        id: "first_green",
        name: "First Green",
        icon: "✓",
        description: "Pass one exercise, including its hidden tests.",
        criteria: { metric: "passedExercises", operator: ">=", value: 1 },
      },
      {
        id: "ten_in_a_row",
        name: "Ten-Line Streak",
        icon: "10",
        description: "Build momentum by passing ten exercises overall.",
        criteria: { metric: "passedExercises", operator: ">=", value: 10 },
      },
      {
        id: "chapter_clear",
        name: "Chapter Clear",
        icon: "◆",
        description: "Pass every exercise in any one chapter.",
        criteria: { metric: "completedChapters", operator: ">=", value: 1 },
      },
      {
        id: "star_50",
        name: "Pocket Constellation",
        icon: "★",
        description: "Collect at least 50 difficulty stars.",
        criteria: { metric: "earnedStars", operator: ">=", value: 50 },
      },
      {
        id: "five_star_solver",
        name: "Five-Star Solver",
        icon: "Ⅴ",
        description: "Pass at least one difficulty-five exercise.",
        criteria: { metric: "highestPassedDifficulty", operator: ">=", value: 5 },
      },
      {
        id: "halfway_pythonic",
        name: "Halfway Pythonic",
        icon: "½",
        description: "Reach 50 percent overall exercise completion.",
        criteria: { metric: "progressPercent", operator: ">=", value: 50 },
      },
      {
        id: "collection_keeper",
        name: "Collection Keeper",
        icon: "{ }",
        description: "Complete Strings & Tuples, Lists, and Dictionaries & Sets.",
        criteria: {
          metric: "chaptersComplete",
          operator: "containsAll",
          value: ["py05", "py06", "py07"],
        },
      },
      {
        id: "recursion_unwound",
        name: "Recursion Unwound",
        icon: "↻",
        description: "Complete every recursion exercise without losing the base case.",
        criteria: {
          metric: "chapterComplete",
          operator: "==",
          value: true,
          chapterId: "py08",
        },
      },
      {
        id: "all_chapters",
        name: "Eleven Keys",
        icon: "⌘",
        description: "Complete all eleven chapters.",
        criteria: { metric: "completedChapters", operator: ">=", value: 11 },
      },
      {
        id: "full_constellation",
        name: "Full Constellation",
        icon: "✦",
        description: "Collect all 239 available difficulty stars.",
        criteria: { metric: "earnedStars", operator: ">=", value: 239 },
      },
    ],

    chapters: {
      py01: {
        title: "First Programs",
        subtitle: "Turn a short specification into a complete input → transform → output program.",
        objectives: [
          "Predict execution order and exact printed output.",
          "Convert keyboard input into useful numeric types.",
          "Translate arithmetic and units without losing meaning.",
        ],
        tutorial: [
          section(
            "Follow the execution story",
            "A script is a sequence of actions. Python starts with the first statement and normally moves downward one statement at a time. Assignment stores a value; print asks Python to turn a value into text and send it to standard output. Read a small program as a timeline: after each line, ask what changed in memory and what became visible. Automated checks compare visible output exactly, so punctuation, capitalization, spaces, and line breaks are part of the interface.",
            "status = \"Oven warming\"\ntemperature = 180\nprint(status)\nprint(temperature)",
            [
              "Trace assignments and output in top-to-bottom order.",
              "Predict every output line before running the code.",
              "Remove temporary debugging messages before submitting.",
            ],
            "Mental model: variables change the program's private state; print exposes selected state to the outside world.",
            "A value can be correct in memory while the answer is still rejected because an extra label, space, or debug line changed stdout.",
          ),
          section(
            "Understand the input boundary",
            "input pauses the script, waits for one line, removes its trailing newline, and returns the remaining characters as a string. That is true even when the user typed digits. Keep text as text when it represents a name or label; convert once near the boundary when it represents a quantity. A prompt is also printed output, so omit prompts when an exercise expects silent input.",
            "nickname = input(\"Choose a nickname: \")\nfavourite_colour = input(\"Favourite colour: \")\nprofile = nickname + \" likes \" + favourite_colour\nprint(profile)",
            [
              "Decide whether each incoming line means text, an integer, or a decimal measurement.",
              "Convert numeric text once, immediately after reading it.",
              "Check whether prompts are permitted by the output contract.",
            ],
            "Boundary rule: read raw text, validate or convert it, then let the core of the program use stable types.",
            "Treating all digit-looking input as a number is also wrong: postal codes and identifiers may need their leading zeroes preserved.",
          ),
          section(
            "Use names to explain the transformation",
            "A variable name should describe meaning and, when useful, the unit. Assignment evaluates the expression on the right first and then binds its result to the name on the left. Small intermediate values turn a dense calculation into checkpoints that can be inspected independently. Constants should be named separately so a reader can distinguish fixed policy from changing data.",
            "slices_per_pizza = 8\npizzas = 3\nreserved_slices = 5\navailable_slices = pizzas * slices_per_pizza - reserved_slices\nprint(available_slices)",
            [
              "Prefer names such as available_slices over single letters in multi-step work.",
              "Separate fixed rules from user-provided values.",
              "Write the value and type after every assignment for one sample run.",
            ],
            "Mental model: each well-named variable is a labelled checkpoint in the data flow.",
            "Reusing one name for unrelated meanings makes an old assumption about its type or unit silently wrong later.",
          ),
          section(
            "Translate a calculation in visible stages",
            "Operators follow precedence rules, but explicit parentheses document the intended grouping. Before calculating, convert quantities to compatible units. Then work one named stage at a time and compare it with a hand-worked example. This separates misunderstandings of the formula from mistakes in Python syntax.",
            "cups_of_flour = 2.5\ntablespoons_per_cup = 16\nextra_tablespoons = 3\ntotal_tablespoons = cups_of_flour * tablespoons_per_cup + extra_tablespoons\nprint(total_tablespoons)",
            [
              "Write the relationship in words before writing operators.",
              "Convert values to one compatible unit before combining them.",
              "Predict a normal case and a zero-sized case by hand.",
            ],
            "The learning loop is predict → run → compare → explain any difference.",
            "A program can run without errors and still be wrong when it combines incompatible units or groups operations incorrectly.",
          ),
        ],
        deepDive: {
          mentalModel: {
            title: "The three-room program",
            body: "Picture a small script as three connected rooms. The input room receives untrusted text, the workbench converts and transforms values, and the output room publishes only the promised result. A bug becomes easier to locate when you can name the room in which reality first differs from your prediction.",
            steps: [
              { label: "Contract", detail: "List each incoming line in order and describe the exact visible result without writing Python yet." },
              { label: "Boundary", detail: "Read text and convert only quantities that genuinely need arithmetic; identifiers can remain strings." },
              { label: "State", detail: "Give every intermediate value a meaningful name and record its expected type and unit." },
              { label: "Transform", detail: "Apply one understandable relationship at a time and check it against a hand-worked example." },
              { label: "Publish", detail: "Print only the contract value; prompts and diagnostic labels are also observable output." },
            ],
          },
          guidedPractice: [
            {
              title: "Build a café collection note",
              prompt: "Read a drink name and a whole-number quantity, then create one clear summary line. Use your own wording so this remains separate from any graded exercise.",
              starterCode: "drink = input()\nquantity_text = input()\n\n# Convert the quantity and build a summary.\n# Print exactly one line.",
              questions: [
                "What types do the two names hold immediately after input()?",
                "Which value needs conversion, and at what boundary should it happen?",
                "How could an extra prompt alter an automated output comparison?",
              ],
              reveal: "A sound plan has three visible stages: capture two strings, convert only the quantity, then construct and print one summary. Predict the final characters before running it; the exact sentence is deliberately yours to design.",
            },
            {
              title: "Trace a time conversion",
              prompt: "Turn a supplied number of whole minutes into a total number of seconds, but first annotate the intended type and unit after every line.",
              starterCode: "minutes_text = input()\n# minutes = ...\nseconds_per_minute = 60\n# total_seconds = ...\n# print the result",
              questions: [
                "Why is multiplying the original text unsafe even though Python permits some string multiplication?",
                "Which name is fixed policy and which name varies per run?",
                "What should happen for zero minutes, and does the same data flow still work?",
              ],
              reveal: "Convert the boundary value to an integer once, keep the fixed conversion factor separate, and derive a newly named total. A zero case should travel through the same stages without a special branch.",
            },
          ],
          glossary: [
            { term: "statement", definition: "One executable instruction, normally processed in source order." },
            { term: "standard input", definition: "The stream from which input() receives text, one requested line at a time." },
            { term: "standard output", definition: "The visible text stream produced by print and compared by many automated tests." },
            { term: "assignment", definition: "Evaluation of a right-hand expression followed by binding its value to a name." },
            { term: "type conversion", definition: "Creating a value of another type, such as turning numeric text into an integer." },
            { term: "expression", definition: "Code that Python evaluates to produce a value." },
          ],
          debugChecklist: [
            "Read the traceback from its final line upward and identify the first failing operation.",
            "Write the value and type produced by every input() call before assuming it is numeric.",
            "Compare the required and observed output with spaces and line breaks made visible.",
            "Check units on both sides of every arithmetic operator.",
            "Temporarily inspect one intermediate value at a time, then remove diagnostics before testing.",
            "Re-run with zero or the smallest valid quantity to expose hidden assumptions.",
          ],
          checkpoint: {
            question: "A user types 12 when the program executes value = input(). What is stored in value?",
            options: ["The integer 12", "The string \"12\"", "A value whose type changes automatically when used", "Two individual integer digits"],
            answerIndex: 1,
            explanation: "input() always returns text. The program must request an explicit conversion when the domain calls for a number.",
          },
        },
        runbook: [
          runStep("1. Read the interface", "Underline what arrives, its order, and exactly what may be printed; prompts count as output.", "A compact input → output sketch with types.", "The input/output contract is the observable behaviour; correct internal arithmetic cannot compensate for reading or printing the wrong shape.", "Replace the story with numbered slots such as input 1, input 2, output 1, then attach meaning and type to each slot."),
          runStep("2. Model the data", "Give each value a meaning and unit, then work through a different sample by hand.", "A table of names, types, units, and predicted values.", "Types prevent invalid operations while units prevent logically invalid ones that Python cannot detect.", "Say each expression aloud with its units; if the sentence sounds impossible, split or convert the quantities before coding."),
          runStep("3. Build in stages", "Keep reading, transformation, and display as three visible regions of the script.", "A trace showing the state after each region.", "Stage boundaries localize mistakes and stop input parsing, domain logic, and presentation from obscuring one another.", "Comment out the output region, confirm the transformation with temporary inspection, then restore a single final print."),
          runStep("4. Probe behaviour", "Try an ordinary value, zero or empty input when valid, and one awkward boundary.", "Expected and observed output recorded side by side.", "A single friendly example proves only one route; boundaries expose conversion, grouping, and formatting assumptions.", "Change only one input dimension per run and predict the direction of the result before pressing Run."),
          runStep("5. Clean the boundary", "Remove diagnostics and compare stdout character by character with the contract.", "Only the required lines, punctuation, and spacing remain.", "Automated judges observe the public stream, so extra helpful text is still a behavioural defect.", "Use repr on your output during debugging to reveal spaces and newlines, then remove that diagnostic call before submission."),
        ],
      },

      py02: {
        title: "Simple Data",
        subtitle: "Represent numbers accurately and translate formulas into testable expressions.",
        objectives: [
          "Choose integer or floating-point operations deliberately.",
          "Translate formulas with correct grouping and rounding.",
          "Use remainder and boolean values in numeric decisions.",
        ],
        tutorial: [
          section(
            "Choose a numeric meaning before an operator",
            "Integers represent exact whole counts. Floating-point values approximate measurements and ratios. The operator should match the question: / asks for a quotient that may contain a fraction, // asks how many complete groups fit, and % asks what remains. For negative operands, // rounds downward rather than toward zero, so confirm that behaviour if signs are allowed.",
            "pages = 53\ndays = 7\nexact_rate = pages / days\ncomplete_daily_sets = pages // days\nunassigned_pages = pages % days\nprint(exact_rate, complete_daily_sets, unassigned_pages)",
            [
              "State whether the result is a count, measurement, ratio, or remainder.",
              "Use / only when a fractional answer has meaning.",
              "Test // and % together to verify dividend == divisor * quotient + remainder.",
            ],
            "Mental model: operators are questions about the data, not interchangeable syntax choices.",
            "Converting a division result to int after the fact can hide the fact that the wrong kind of division was chosen.",
          ),
          section(
            "Preserve the structure of a formula",
            "Translate mathematical notation from the outside inward. Name quantities that carry meaning and subexpressions that are reused. Parentheses should reveal the intended grouping even when precedence would technically produce the same value. Once the code mirrors the written formula, a hand calculation can validate each stage independently.",
            "mass_kg = 72\nspeed_mps = 4.5\nspeed_squared = speed_mps ** 2\nkinetic_energy_joules = 0.5 * mass_kg * speed_squared\nprint(kinetic_energy_joules)",
            [
              "Write the formula with units before translating it.",
              "Compute meaningful repeated subexpressions only once.",
              "Check a simple case whose result can be derived mentally.",
            ],
            "Named stages make mathematical intent reviewable and localize mistakes.",
            "A compact one-line formula may be syntactically valid while silently using the wrong grouping or unit.",
          ),
          section(
            "Separate precision from presentation",
            "round returns a numeric value rounded to a requested precision, while an f-string format controls the characters displayed. Keep full internal precision through the calculation unless the rules explicitly require staged rounding. At the boundary, decide whether tests expect a number-like representation or a fixed-width piece of text.",
            "litres_shared = 7 / 9\nrounded_litres = round(litres_shared, 3)\nlabel = f\"{litres_shared:.3f} L\"\nprint(rounded_litres)\nprint(label)",
            [
              "Locate the exact stage where the contract asks for rounding.",
              "Distinguish a float result from formatted text.",
              "Test a value whose formatted form needs trailing zeroes.",
            ],
            "Precision controls the value; formatting controls its visible representation.",
            "Repeatedly rounding intermediate values compounds error and can move the final result across a boundary.",
          ),
          section(
            "Use remainder to model repeating states",
            "Modulo maps an unbounded count into a fixed cycle. It can identify a position inside a repeating pattern, wrap an index, or test whether a complete group has no remainder. Write the possible remainder values first, then map each one to a meaning. Boundary cases occur immediately before, at, and after a full cycle.",
            "pattern = (\"red\", \"amber\", \"green\", \"blue\")\nstep_number = 14\npattern_index = step_number % len(pattern)\nactive_colour = pattern[pattern_index]\nprint(active_colour)",
            [
              "List all legal remainder values for the cycle.",
              "Explain what remainder zero means in this domain.",
              "Test one position before and after a wrap.",
            ],
            "Mental model: modulo folds a number line into a repeating ring of positions.",
            "Using a fixed cycle length in several places creates inconsistent behaviour when the pattern later changes; derive it with len.",
          ),
        ],
        runbook: [
          runStep("1. Classify quantities", "Label each value as a count, measurement, ratio, remainder, or formatted string.", "A justified Python type and unit for every value."),
          runStep("2. Translate the rule", "Preserve grouping with named stages instead of compressing the formula immediately.", "A hand trace from inputs through intermediate values."),
          runStep("3. Map the domain", "Identify zero divisors, invalid roots, sign assumptions, and cycle boundaries before calculation.", "A short list of legal and illegal cases."),
          runStep("4. Control precision", "Keep full precision internally and round or format only at the stated boundary.", "Raw, rounded, and displayed values compared deliberately."),
          runStep("5. Stress the edges", "Test zero, negative values when permitted, an exact group, and values beside a threshold.", "Expected results explained from the mathematical model."),
        ],
      },

      py03: {
        title: "Flow, Conditionals & Iteration",
        subtitle: "Control which statements run, how often they run, and what remains true during repetition.",
        objectives: [
          "Design branches with explicit priority.",
          "State and preserve loop invariants.",
          "Validate inputs and reason about termination.",
        ],
        tutorial: [
          section(
            "Turn a decision table into branches",
            "Conditionals select one path from several possibilities. Before coding, write rows containing a condition and its outcome, then order those rows from exceptional or narrow cases to the general case. In an if/elif/else chain, Python stops at the first true condition, so overlap and order are part of the behaviour rather than formatting choices.",
            "parcel_weight = 7.5\nif parcel_weight <= 0:\n    shipping = \"invalid\"\nelif parcel_weight <= 2:\n    shipping = \"letter rate\"\nelif parcel_weight <= 10:\n    shipping = \"standard rate\"\nelse:\n    shipping = \"freight rate\"\nprint(shipping)",
            [
              "Write every case and outcome before the if statement.",
              "Mark overlapping conditions and decide which has priority.",
              "Test just below, exactly at, and just above each boundary.",
            ],
            "Mental model: an elif chain is a top-to-bottom gate; only the first open gate is entered.",
            "Several independent if statements can run several outcomes when the rules were intended to be mutually exclusive.",
          ),
          section(
            "Give every loop state, progress, and a stop",
            "A while loop repeatedly checks its condition before entering the body. Describe what each control variable means at the top of an iteration, identify the update that changes it, and explain why that update eventually makes the condition false. A short trace table with iteration, state before, action, and state after is often enough to expose a missing update.",
            "crates_remaining = 12\ntruck_capacity = 5\nwhile crates_remaining > 0:\n    loaded_now = min(truck_capacity, crates_remaining)\n    print(\"loading\", loaded_now)\n    crates_remaining -= loaded_now",
            [
              "State the loop condition in plain language.",
              "Point to a state change that guarantees progress on every path.",
              "Trace the first iteration and the final partial iteration.",
            ],
            "Loop proof: the state stays valid, a measure moves toward its bound, and the bound eventually stops repetition.",
            "If continue skips the progress update, an apparently reasonable loop can repeat the same state forever.",
          ),
          section(
            "Accumulators remember processed work",
            "A for loop visits source items one at a time. An accumulator summarizes everything seen so far: an output list stores accepted transformations, a number stores a total, and a boolean stores a claim that remains true. Choose an initial value that correctly represents processing zero items, then state the invariant after each append or update.",
            "temperatures = [18, 21, 17, 24]\nwarmer_readings = []\nfor reading in temperatures:\n    if reading >= 20:\n        warmer_readings.append(reading)\nprint(warmer_readings)",
            [
              "Describe what the accumulator contains after k source items.",
              "Initialize it once, before the loop.",
              "Update it only when the current item satisfies the stated rule.",
            ],
            "Mental model: after each iteration, the accumulator is the complete answer for the prefix already visited.",
            "Appending to the source while iterating over it can extend the work unexpectedly; accumulate into a separate result.",
          ),
          section(
            "Control nested search with decisive evidence",
            "Nested loops are appropriate when each outer item owns a separate inner search. Reset inner state for every new outer item. If one match completely answers the current search, break only the inner loop and preserve a flag or result that explains what was found. Validate the overall shape before entering expensive repeated work.",
            "seats = [[\"taken\", \"taken\"], [\"taken\", \"open\"]]\nfirst_open = None\nfor row_index, row in enumerate(seats):\n    for seat_index, state in enumerate(row):\n        if state == \"open\":\n            first_open = (row_index, seat_index)\n            break\n    if first_open is not None:\n        break\nprint(first_open)",
            [
              "Give the outer and inner loops different, explicit responsibilities.",
              "Reset per-row or per-candidate state at the correct level.",
              "Use break only when later work cannot improve the required answer.",
            ],
            "Structure search around evidence: continue while evidence is incomplete and stop once it is decisive.",
            "A break exits only its nearest loop; assuming it exits every nesting level produces subtle extra work or a replaced result.",
          ),
        ],
        runbook: [
          runStep("1. Enumerate paths", "Build a table of conditions, outcomes, overlaps, and priority before writing branches.", "One representative and one boundary value per row."),
          runStep("2. Define loop state", "Explain every control variable and accumulator at the top of an iteration.", "A one-sentence invariant for each loop level."),
          runStep("3. Prove progress", "Show that every repeated path changes a finite measure toward termination.", "A three-row trace plus the final state."),
          runStep("4. Place exits", "Decide where validation, continue, break, and early results are justified by decisive evidence.", "Each exit annotated with why later work is unnecessary."),
          runStep("5. Cover boundaries", "Exercise every branch, empty or smallest ranges, and the exact final iteration.", "Expected and observed state transitions, not only final output."),
        ],
      },

      py04: {
        title: "Functions",
        subtitle: "Build small, reusable contracts with explicit inputs, outputs, and failure behaviour.",
        objectives: [
          "Separate calculation from display and input.",
          "Decompose algorithms into focused helpers.",
          "Make every return path satisfy one stable contract.",
        ],
        tutorial: [
          section(
            "Start from a precise callable contract",
            "A function contract names accepted inputs, the meaning and type of the return value, side effects, and behaviour at the boundaries. Write that promise before the body. The implementation may change, but callers should not need to know how the result is produced. A useful docstring describes the semantic rule rather than narrating individual lines.",
            "def clamp(value, lower, upper):\n    \"\"\"Return value constrained to the inclusive interval.\"\"\"\n    if value < lower:\n        return lower\n    if value > upper:\n        return upper\n    return value",
            [
              "State each parameter's meaning and valid domain.",
              "State one stable return type and any sentinel explicitly.",
              "Say whether caller-owned data may be modified.",
            ],
            "Mental model: a function is a small machine with an input socket, an output socket, and an explicit promise between them.",
            "A branch with no return silently produces None, violating a contract even when the popular path works.",
          ),
          section(
            "Return data; display it at the boundary",
            "return hands a value back to the caller and immediately ends that function call. print writes text to stdout and itself returns None. Keeping calculation functions free of display lets other code test, compare, store, or format the returned value. A command-line wrapper may print the result, but that is a separate responsibility.",
            "def rectangle_perimeter(width, height):\n    return 2 * (width + height)\n\nperimeter = rectangle_perimeter(8, 3)\nprint(f\"Border needed: {perimeter} m\")",
            [
              "Use return for the value promised by the contract.",
              "Keep labels and presentation outside the calculation function.",
              "Assert both the returned value and its type.",
            ],
            "Pure core, visible shell: compute reusable data inside and format it only where people or files are involved.",
            "A function that prints the right-looking answer may still give its caller only None.",
          ),
          section(
            "Use helpers to name separate ideas",
            "Extract a helper when a transformation has a clear name, an independent contract, or more than one caller. This lowers the number of ideas held in mind at once. The public function should read like a short explanation that delegates details, while each helper remains small enough to test with a few focused examples.",
            "def hexadecimal_channel(pair):\n    return int(pair, 16)\n\ndef colour_brightness(hex_colour):\n    red = hexadecimal_channel(hex_colour[1:3])\n    green = hexadecimal_channel(hex_colour[3:5])\n    blue = hexadecimal_channel(hex_colour[5:7])\n    return round((red + green + blue) / 3)",
            [
              "Name the concept the helper owns in a verb or noun phrase.",
              "Pass required data explicitly instead of reading distant globals.",
              "Test the helper before composing it into the public function.",
            ],
            "Good decomposition makes the function names read like the vocabulary of the explanation.",
            "Extracting arbitrary chunks merely to shorten a function creates helpers with unclear contracts and hidden coupling.",
          ),
          section(
            "Guard assumptions, then test from the outside",
            "A guard clause handles an invalid, empty, or already-complete case before the main path. This keeps the normal flow shallow and makes failure behaviour explicit. Black-box tests call only the public function and verify its contract with ordinary values, each boundary, and inputs that activate every guard.",
            "def safe_ratio(numerator, denominator):\n    if not isinstance(numerator, (int, float)):\n        return None\n    if not isinstance(denominator, (int, float)) or denominator == 0:\n        return None\n    return numerator / denominator\n\nassert safe_ratio(9, 3) == 3\nassert safe_ratio(9, 0) is None",
            [
              "Check assumptions before operations that depend on them.",
              "Give every guard a documented return value or exception.",
              "Test one case through every return path.",
            ],
            "A guard protects the core; a black-box test proves the caller-visible promise.",
            "A broad except clause can turn genuine coding defects into misleading fallback values; guard known conditions deliberately.",
          ),
        ],
        runbook: [
          runStep("1. Specify the promise", "Write parameter meanings, valid domains, return type, sentinel behaviour, and mutation policy.", "A docstring plus several input → return examples."),
          runStep("2. Decompose by idea", "Name independently explainable transformations before extracting helpers.", "A dependency sketch with one responsibility per function."),
          runStep("3. Guard the boundary", "Handle invalid, empty, and already-complete states before the normal path.", "One explicit, documented outcome per guard."),
          runStep("4. Compose and return", "Pass values between helpers and ensure every path returns the promised type.", "No display logic or accidental fall-through in the core."),
          runStep("5. Test as a caller", "Exercise normal, boundary, invalid, and side-effect cases through the public function.", "Black-box assertions plus input snapshots when mutation matters."),
        ],
      },

      py05: {
        title: "Strings & Tuples",
        subtitle: "Transform immutable sequences through indexes, parsing, and deliberate reconstruction.",
        objectives: [
          "Use indexing and slicing without off-by-one errors.",
          "Separate parsing, transformation, and formatting.",
          "Traverse flat and nested immutable data safely.",
        ],
        tutorial: [
          section(
            "Think of indexes as positions and slices as gaps",
            "A string index selects one character: zero is the first position and -1 is the final position. A slice selects the region between two gaps, includes its start, and excludes its stop. Drawing characters above indexes and gaps prevents most off-by-one mistakes. Because strings and tuples are immutable, every slice and concatenation creates a new value rather than editing the original.",
            "filename = \"field-notes.csv\"\nextension = filename[-4:]\nstem = filename[:-4]\nalternate_letters = stem[::2]\nprint(stem, extension, alternate_letters)",
            [
              "Draw positive and negative indexes on a sample sequence.",
              "Describe each slice in words before running it.",
              "Check length before using a fixed index whose existence is not guaranteed.",
            ],
            "Mental model: indexes point at elements; slice boundaries point at the gaps around them.",
            "A negative slice boundary is still calculated from the end; on short inputs it may select a surprising but valid empty region instead of raising.",
          ),
          section(
            "Parse structure before transforming text",
            "Delimiters encode structure inside a flat string. split turns that external representation into meaningful fields, a middle stage cleans or transforms each field, and join creates the final representation once. Decide whether empty fields are valid and whether surrounding whitespace belongs to data before choosing the cleanup rule.",
            "raw_tags = \" urgent | backend | needs review \"\ntags = raw_tags.split(\"|\")\nclean_tags = [tag.strip().upper() for tag in tags]\nlabel = \" / \".join(clean_tags)\nprint(label)",
            [
              "Write down the delimiter and policy for empty pieces.",
              "Transform one representative field before mapping the rule to all fields.",
              "Choose the final separator and join exactly once.",
            ],
            "Mental model: parse expands text into structure; format compresses structure back into text.",
            "Calling strip on the entire string removes only its outer whitespace, not whitespace around every internal field.",
          ),
          section(
            "Build transformed text without mutating it",
            "Since a string cannot be changed in place, visit its characters and append transformed pieces to a separate list, then join once. Each branch should decide the replacement for exactly one character. This makes preservation rules explicit: characters not selected for transformation should normally pass through unchanged.",
            "announcement = \"Gate A opens soon\"\npieces = []\nfor character in announcement:\n    if character.lower() in \"aeiou\":\n        pieces.append(\"*\")\n    else:\n        pieces.append(character)\nmasked = \"\".join(pieces)\nprint(masked)",
            [
              "Define the one-character transformation rule in plain language.",
              "Initialize the output builder once before traversal.",
              "Test uppercase, lowercase, spaces, and punctuation.",
            ],
            "Builder pattern: decide one output piece per input piece, then assemble the immutable result once.",
            "Repeatedly concatenating a long string inside a loop creates many temporary strings; collecting pieces and joining is clearer and scales better.",
          ),
          section(
            "Use tuple shape as part of the model",
            "A tuple communicates a fixed record or an immutable grouping. Position has meaning, so unpack fields into names as soon as their shape is known. Nested tuples express records containing grouped subvalues; document that shape and keep the return shape stable. Use indexing for genuinely positional data and named structures when fields become numerous or ambiguous.",
            "book = (\"The Left Hand of Darkness\", 1969, (\"science fiction\", \"classic\"))\ntitle, year, categories = book\nprimary_category, secondary_category = categories\nprint(title)\nprint(year, primary_category, secondary_category)",
            [
              "Write the expected tuple shape before unpacking.",
              "Use descriptive names for positional fields.",
              "Test an empty nested group and reject malformed shapes deliberately.",
            ],
            "Mental model: a tuple is a small fixed schema whose positions carry meaning.",
            "Packing unrelated values into a long tuple makes positional mistakes easy and leaves callers guessing what each index means.",
          ),
        ],
        runbook: [
          runStep("1. Draw the representation", "Mark indexes, slice gaps, delimiters, and nested tuple shape on a non-exercise example.", "An annotated sequence or record diagram."),
          runStep("2. Define edge policy", "Decide behaviour for empty, short, malformed, and delimiter-heavy input before indexing.", "A small edge-case table with stable return types."),
          runStep("3. Parse once", "Turn external text into fields or unpack a fixed tuple into meaningful names.", "Structured intermediate data whose shape is documented."),
          runStep("4. Construct anew", "Traverse immutable input and collect output pieces without trying to mutate it.", "A new string or tuple with the original unchanged."),
          runStep("5. Format exactly", "Join or pack the result once and verify separators, case, whitespace, and order.", "Character-accurate output plus an original-input snapshot."),
        ],
      },

      py06: {
        title: "Lists",
        subtitle: "Use mutable sequences intentionally, with clear ownership and index discipline.",
        objectives: [
          "Choose when to mutate, copy, or construct a new list.",
          "Reason about indexes after insertions and removals.",
          "Apply stacks, matrices, and circular indexing.",
        ],
        tutorial: [
          section(
            "Decide who owns a mutable list",
            "Assignment copies a reference, not the list object. If two names reference the same list, append, pop, item assignment, and other mutation through either name are visible through both. Make a shallow copy when the outer list must be independent; nested objects remain shared unless they are copied too. Treat the choice between mutation and a new result as part of the function contract.",
            "shopping = [\"rice\", \"beans\"]\nplanned = shopping.copy()\nplanned.append(\"lemons\")\nprint(shopping)\nprint(planned)",
            [
              "State whether callers should observe mutation.",
              "Use is to check identity and == to check equal contents.",
              "Snapshot the original before and after a transformation test.",
            ],
            "Mental model: a name is a label pointing to an object; mutation changes the object, not merely the label.",
            "A shallow copy duplicates only the outer container, so editing an inner list can still change data visible from the original.",
          ),
          section(
            "Partition sequences with slice boundaries",
            "List slices produce new outer lists and preserve element order. A boundary can separate a header from its payload, processed work from pending work, or fixed-size pages from remaining items. Compute the boundary once, name both partitions, and remember that the stop is exclusive. Concatenation creates another new list rather than extending either source.",
            "queue = [\"A17\", \"B04\", \"C22\", \"D11\", \"E09\"]\nbatch_size = 2\ncurrent_batch = queue[:batch_size]\nwaiting = queue[batch_size:]\nprint(current_batch)\nprint(waiting)",
            [
              "Describe what lies before and after the slice boundary.",
              "Test a boundary of zero, one, and greater than the list length.",
              "Decide whether nested element sharing is acceptable.",
            ],
            "Mental model: slicing draws a non-destructive boundary through an ordered collection.",
            "Assuming a slice deep-copies nested elements can lead to unexpected shared mutation later.",
          ),
          section(
            "Rebuild when membership changes during traversal",
            "Deleting an element shifts every later element one position left. A for loop over that same list may then skip the item that moved into the current position. When the goal is to keep items satisfying a rule, constructing a new list is usually safer. When in-place deletion is required, traverse indexes backward or control the index explicitly.",
            "tasks = [\n    {\"title\": \"backup\", \"expired\": False},\n    {\"title\": \"old report\", \"expired\": True},\n    {\"title\": \"deploy\", \"expired\": False},\n]\nactive_tasks = [task for task in tasks if not task[\"expired\"]]\nprint(active_tasks)",
            [
              "State whether the source must survive unchanged.",
              "Prefer a new result when selection is the real operation.",
              "If mutating, trace indexes after each deletion.",
            ],
            "After structural mutation, every saved later index describes the old shape and must be reconsidered.",
            "Calling remove deletes the first equal value, not necessarily the specific object or position the algorithm intended.",
          ),
          section(
            "Choose a list role and protect its invariant",
            "A list can be a sequence, output builder, stack, queue-like buffer, or grid. Name the role because it determines legal operations. In a stack, append pushes and pop removes the most recent item; its invariant concerns the history still available. For a grid, each nested list is a row and rectangular shape must be checked before column indexing.",
            "undo_stack = []\ndocument = \"draft\"\nundo_stack.append(document)\ndocument = \"revised draft\"\nundo_stack.append(document)\ndocument = \"final draft\"\nprevious_version = undo_stack.pop()\nprint(previous_version)",
            [
              "Name whether the list represents order, history, output, or coordinates.",
              "State what the final element means before using pop.",
              "Check non-empty state before reading or removing the top item.",
            ],
            "Mental model: the data structure's role is a promise about what every position means after each operation.",
            "Using pop(0) repeatedly as a queue shifts all later items each time; collections.deque is better for large front removals.",
          ),
        ],
        runbook: [
          runStep("1. Declare ownership", "Decide whether caller input may change and whether nested elements are shared.", "An explicit in-place, shallow-copy, or new-result policy."),
          runStep("2. Name the role", "Identify the list as ordered data, builder, stack, queue, or grid.", "A one-sentence invariant for every position used."),
          runStep("3. Trace structural edits", "Draw indexes before and after each append, pop, insert, slice, or deletion.", "A small transition table that exposes shifting positions."),
          runStep("4. Challenge the shape", "Test empty, one-item, duplicate, nested, and ragged inputs when permitted.", "Shape-specific expected outcomes and guarded failures."),
          runStep("5. Verify aliasing", "Compare identities, values, and caller snapshots after the operation.", "Evidence that mutation and sharing match the declared policy."),
        ],
      },

      py07: {
        title: "Dictionaries & Sets",
        subtitle: "Model identity, frequency, membership, and relationships with hash-based collections.",
        objectives: [
          "Choose stable dictionary keys and dependable defaults.",
          "Use set algebra for membership questions.",
          "Handle ties, missing keys, mutation, and ordering explicitly.",
        ],
        tutorial: [
          section(
            "Design keys around the lookup question",
            "A dictionary maps each unique, hashable key to one value. Start by completing the sentence 'given this ___, I need that ___.' The first blank is usually the key. Keys should be stable identifiers; values may be simple facts or richer records. Assignment to an existing key replaces its value, while reading a missing key with brackets raises KeyError.",
            "stock_by_sku = {\"PEN-BLU\": 24, \"NOTE-A5\": 11}\nshipment = {\"PEN-BLU\": 8, \"ERASER-WHT\": 6}\nfor sku, quantity in shipment.items():\n    previous = stock_by_sku.get(sku, 0)\n    stock_by_sku[sku] = previous + quantity\nprint(stock_by_sku)",
            [
              "Write the lookup sentence before choosing the key.",
              "Choose an immutable, canonical identifier.",
              "Document the meaning and type of every stored value.",
            ],
            "Mental model: a dictionary is an index you design for a specific retrieval question.",
            "Using display names as keys can merge distinct records when names are not guaranteed unique.",
          ),
          section(
            "Group related records deliberately",
            "A dictionary value can itself be a list, set, or record. Grouping is a two-stage operation: obtain the collection for a key, then update that collection. setdefault can create the initial collection, but an explicit membership branch may be clearer while learning. Decide whether repeated values should be preserved, removed, or counted before choosing the nested type.",
            "books = [(\"Ada\", \"Algorithms\"), (\"Lin\", \"Networks\"), (\"Ada\", \"Compilers\")]\nbooks_by_reader = {}\nfor reader, title in books:\n    books_by_reader.setdefault(reader, []).append(title)\nprint(books_by_reader[\"Ada\"])",
            [
              "Choose list, set, or number from the required duplicate semantics.",
              "Initialize a fresh nested collection for each new key.",
              "Test multiple records for one key and a key with one record.",
            ],
            "Mental model: the outer dictionary finds a group; the nested value represents the group according to explicit rules.",
            "Using the same pre-created list as the default for several keys makes all those keys share one mutable collection.",
          ),
          section(
            "Translate membership rules into set algebra",
            "A set stores distinct hashable values and intentionally discards order and duplicate counts. Intersection answers what belongs to both groups, union answers what belongs to either, and difference answers what belongs to the left group but not the right. Draw a small Venn diagram first, then choose the operator matching the shaded region.",
            "requested = {\"read\", \"write\", \"deploy\"}\nrole_permissions = {\"read\", \"write\", \"comment\"}\ngranted = requested & role_permissions\ndenied = requested - role_permissions\nprint(\"granted:\", sorted(granted))\nprint(\"denied:\", sorted(denied))",
            [
              "Confirm that order and multiplicity do not carry meaning.",
              "Name the left and right operands in a directional difference.",
              "Sort only at the display boundary when deterministic order is required.",
            ],
            "Mental model: set operations calculate regions of a membership diagram.",
            "A - B and B - A answer different questions; treating difference as symmetric loses direction.",
          ),
          section(
            "Separate absence, falsey values, and mutation",
            "A missing key is different from a present key holding 0, False, an empty string, or None. Use key in mapping when presence itself matters and get when a documented fallback is appropriate. Copy caller-owned mappings before destructive cleanup. If output order is part of the contract, sort keys or items explicitly rather than relying on incidental construction order.",
            "settings = {\"theme\": \"night\", \"autosave\": False, \"legacy_mode\": True}\nworking = settings.copy()\nautosave_is_configured = \"autosave\" in working\nautosave_value = working.get(\"autosave\", True)\nworking.pop(\"legacy_mode\", None)\nprint(autosave_is_configured, autosave_value)\nprint(settings)",
            [
              "Decide whether absence and a falsey stored value mean different things.",
              "Use a documented default rather than an accidental one.",
              "Snapshot caller data before deletion or replacement.",
            ],
            "Lookup semantics, ownership, and ordering are three separate contracts; make each explicit.",
            "Testing if mapping.get(key) merges a missing key with any present falsey value and can select the wrong branch.",
          ),
        ],
        runbook: [
          runStep("1. Model the question", "Write what must be retrieved, grouped, or compared and which facts identify it.", "A key → value schema or labelled membership diagram."),
          runStep("2. Normalize identifiers", "Canonicalize case, whitespace, and representation before creating keys or set members.", "Equivalent real-world values become equal Python values."),
          runStep("3. Choose duplicate semantics", "Decide whether repeats are preserved, discarded, counted, or grouped.", "A justified choice of list, set, number, or nested record."),
          runStep("4. Resolve ambiguity", "Specify missing-key defaults, falsey stored values, ties, and output ordering separately.", "Deterministic results for ambiguous examples."),
          runStep("5. Protect ownership", "Copy before destructive updates unless mutation is part of the contract.", "Caller snapshots and ordered output evidence."),
        ],
      },

      py08: {
        title: "Recursion",
        subtitle: "Solve a problem by reducing it to smaller instances with a direct stopping answer.",
        objectives: [
          "Define base cases and prove recursive progress.",
          "Trace values while the call stack unwinds.",
          "Recognize structural recursion and branching search.",
        ],
        tutorial: [
          section(
            "Pair a base case with a progress measure",
            "Recursion solves a problem by asking the same function to solve a strictly smaller version. The base case answers the smallest valid version directly. Before coding, name a measure—such as exponent, remaining length, or tree depth—that decreases on every recursive path and cannot decrease forever. This is the termination proof.",
            "def integer_power(base, exponent):\n    if exponent == 0:\n        return 1\n    return base * integer_power(base, exponent - 1)\n\nprint(integer_power(3, 4))",
            [
              "Write the direct answer for the smallest valid problem.",
              "Name the non-negative measure that strictly decreases.",
              "Check every branch, not only the common one, for progress.",
            ],
            "Mental model: each call holds one unfinished multiplication while delegating a smaller exponent to the next stack frame.",
            "Allowing a negative exponent without a matching rule makes exponent - 1 move away from the base forever.",
          ),
          section(
            "Trace descent and unwind separately",
            "During descent, each call records its local values and waits for a smaller call. When the base returns, suspended expressions resume in reverse order. A useful trace has two columns: calls going down and substitutions coming back up. This reveals whether work belongs before the recursive call, after it, or in both places.",
            "def triangular_total(number):\n    if number == 0:\n        return 0\n    smaller_total = triangular_total(number - 1)\n    return number + smaller_total\n\n# descent: 4, 3, 2, 1, 0\n# unwind:  0, 1, 3, 6, 10",
            [
              "Expand calls until the first direct return.",
              "Record one local frame per call rather than overwriting values mentally.",
              "Substitute return values upward in reverse call order.",
            ],
            "Recursive evaluation has two stories: reducing the problem and combining the returned answers.",
            "Printing only during descent can make it look as if nothing happens during unwind, where the result may actually be assembled.",
          ),
          section(
            "Let recursive code mirror recursive data",
            "Tree-shaped data contains smaller values of the same overall kind. Define every node shape: here a file is a leaf with a direct size, while a directory contains child nodes whose sizes must be combined. Return the same type from every shape so the parent can combine child results without special cases.",
            "def storage_used(node):\n    if node[\"kind\"] == \"file\":\n        return node[\"bytes\"]\n    total = 0\n    for child in node[\"children\"]:\n        total += storage_used(child)\n    return total\n\nproject = {\"kind\": \"folder\", \"children\": [\n    {\"kind\": \"file\", \"bytes\": 120},\n    {\"kind\": \"file\", \"bytes\": 80},\n]}\nprint(storage_used(project))",
            [
              "List every legal node shape and its direct data.",
              "Return one consistent type from leaves and containers.",
              "Test an empty container, one leaf, and several nesting levels.",
            ],
            "Mental model: the data definition is the blueprint for the recursive branches.",
            "Failing to distinguish a leaf from a container before reading children causes missing-key or type errors at the deepest level.",
          ),
          section(
            "Cache repeated states in a branching graph",
            "Branching recursion explores several smaller choices. Different branches may arrive at the same state, causing repeated work. Define the state with immutable values, cache its completed answer, and ensure the dependency graph has no cycles. Also estimate maximum stack depth separately from total call count; caching reduces repeated calls but does not automatically reduce depth.",
            "from functools import lru_cache\n\ndependencies = {\n    \"web\": (\"api\", \"ui\"),\n    \"api\": (\"database\",),\n    \"ui\": (\"theme\",),\n}\n\n@lru_cache(maxsize=None)\ndef dependency_depth(package):\n    children = dependencies.get(package, ())\n    if not children:\n        return 1\n    return 1 + max(dependency_depth(child) for child in children)\n\nprint(dependency_depth(\"web\"))",
            [
              "Describe the entire state using immutable cacheable arguments.",
              "Identify where different branches can revisit that same state.",
              "Detect or forbid cycles and estimate maximum depth.",
            ],
            "Memoization changes repeated exploration into one computation per distinct state.",
            "Caching a function that depends on hidden mutable global state can return stale answers even when its arguments match.",
          ),
        ],
        runbook: [
          runStep("1. Define direct cases", "List every smallest number, empty shape, or leaf that can be answered without another call.", "Base cases with types and expected returns."),
          runStep("2. Prove progress", "Name a bounded measure that strictly shrinks on every recursive path.", "A sentence explaining why the base must be reached."),
          runStep("3. Express smaller work", "Build the current answer only from legal, smaller subproblems with consistent result types.", "A recurrence or data-shape rule in plain language."),
          runStep("4. Trace both directions", "Record stack frames during descent and substitute values during unwind.", "An annotated call tree with downward and upward arrows."),
          runStep("5. Budget resources", "Estimate distinct states, repeated states, total calls, and maximum depth.", "A justified choice among plain recursion, memoization, and iteration."),
        ],
      },

      py09: {
        title: "FP with Collections",
        subtitle: "Describe collection work as composable selection, transformation, reduction, and lazy production.",
        objectives: [
          "Design clear filter → map → reduce pipelines.",
          "Write focused, pure callback functions.",
          "Control when lazy iterators are consumed.",
        ],
        tutorial: [
          section(
            "Sketch data stages before choosing syntax",
            "A collection pipeline describes movement from a source through focused stages: select items, transform each survivor, and optionally combine or materialize the results. Write the value type at every arrow and explain one rejected and one accepted item. Only then choose filter, map, a comprehension, reduce, or a generator for each stage.",
            "filenames = [\"app.py\", \"notes.txt\", \"tests.py\", \"README.md\"]\n# strings -> Python filenames -> display labels -> list\npython_files = filter(lambda name: name.endswith(\".py\"), filenames)\nlabels = map(lambda name: name.removesuffix(\".py\").upper(), python_files)\nresult = list(labels)\nprint(result)",
            [
              "Annotate source, intermediate, and final types.",
              "Give each stage one verb and one responsibility.",
              "Trace one value that survives and one that is rejected.",
            ],
            "Mental model: a pipeline is an assembly line; each station receives one kind of value and emits another.",
            "Reordering stages can change meaning, raise errors for values that should have been rejected, or do unnecessary work.",
          ),
          section(
            "Keep predicates and transformations single-purpose",
            "A filter predicate receives one item and returns a truth value answering whether it survives. A map callback receives one item and returns its replacement. Small named functions are often clearer than long lambdas, especially when normalization has several steps. Keep callbacks free of external mutation so the same input always produces the same stage behaviour.",
            "accounts = [\"  ADA \" , \"\", \"  lin\", \"grace  \"]\n\ndef has_name(raw_name):\n    return bool(raw_name.strip())\n\ndef normalize_name(raw_name):\n    return raw_name.strip().casefold()\n\nactive_names = filter(has_name, accounts)\nnormalized_names = map(normalize_name, active_names)\nprint(list(normalized_names))",
            [
              "Make the predicate answer one yes/no question.",
              "Make the mapper produce one replacement value.",
              "Test callbacks independently before composing them.",
            ],
            "One-item callbacks are reusable, testable vocabulary for a larger pipeline.",
            "A callback that appends elsewhere and returns nothing causes map to yield None while hiding the actual result in external state.",
          ),
          section(
            "Fold only when the accumulator has a clear meaning",
            "reduce combines a stream into one accumulator. State what the accumulator means after processing the first k items and choose an initializer that also defines empty-input behaviour. Prefer a purpose-built operation such as sum, min, max, any, all, or join when it expresses the same intention more directly.",
            "from functools import reduce\n\ndef choose_longer(current, candidate):\n    if len(candidate) > len(current):\n        return candidate\n    return current\n\nlabels = [\"ok\", \"processing\", \"done\"]\nlongest_label = reduce(choose_longer, labels, \"\")\nprint(longest_label)",
            [
              "Write the accumulator invariant in one sentence.",
              "Define what empty input should return through the initializer.",
              "Use a named reducer when tie or branch rules need explanation.",
            ],
            "Mental model: each item and the answer-so-far become the next answer-so-far.",
            "An initializer with the wrong type can make the reducer's first call inconsistent with all later calls.",
          ),
          section(
            "Generators let consumers pull values on demand",
            "Calling a generator function creates an iterator without executing its body. Each next request resumes execution until yield, returns that value, and pauses while preserving local state. This enables early stopping and bounded memory, but the iterator is normally single-use. Keep file handles or mutable sources in mind because consumption may happen later than creation.",
            "def nonblank_lines(lines):\n    for line in lines:\n        cleaned = line.strip()\n        if cleaned:\n            yield cleaned\n\nstream = nonblank_lines([\" alpha \", \"   \", \"beta\"] )\nprint(next(stream))\nprint(list(stream))",
            [
              "Define one logical value per yield.",
              "Test creation, one next call, and remaining consumption separately.",
              "Create a fresh iterator when a second traversal is required.",
            ],
            "Mental model: a generator is a paused producer whose consumer controls the clock.",
            "Converting a generator to a list for inspection exhausts it; later iteration sees no values.",
          ),
        ],
        runbook: [
          runStep("1. Diagram stages", "Write source → select → transform → combine or yield, with a type at each arrow.", "A pipeline sketch plus one traced source item."),
          runStep("2. Isolate callbacks", "Give predicates, mappers, and reducers one responsibility and test them separately.", "Tiny assertions for accepted, rejected, and transformed items."),
          runStep("3. Compose semantically", "Order stages from domain meaning, then verify that rejected values never reach unsafe transformations.", "A small end-to-end trace through every stage."),
          runStep("4. Choose evaluation time", "Decide whether callers need a concrete collection now or a one-use iterator later.", "An explicit and justified materialization point."),
          runStep("5. Probe lifecycle", "Test empty input, all-rejected input, duplicates, partial consumption, and attempted reuse.", "Expected values plus iterator state at each step."),
        ],
      },

      py10: {
        title: "Effect-Free Programming",
        subtitle: "Build transformations that are predictable because inputs and external state remain untouched.",
        objectives: [
          "Recognize and isolate side effects.",
          "Create new values with comprehensions and generators.",
          "Use closures without hidden mutable surprises.",
        ],
        tutorial: [
          section(
            "Draw a boundary around effects",
            "Input, print, files, time, randomness, network calls, and mutation all connect code to changing state. A pure function depends only on its arguments, returns a value, and leaves caller-owned objects untouched. Keep effects in a thin outer layer and pass ordinary values into a deterministic core. This makes repeated calls and tests independent of the environment.",
            "def translate_points(points, horizontal, vertical):\n    return [\n        (x + horizontal, y + vertical)\n        for x, y in points\n    ]\n\nsource = [(1, 2), (4, -1)]\nmoved = translate_points(source, 3, 5)\nassert source == [(1, 2), (4, -1)]\nprint(moved)",
            [
              "Inventory every external read, write, and mutation.",
              "Define ownership of mutable arguments before implementation.",
              "Pass changing environmental data in as explicit values.",
            ],
            "Mental model: a pure core is a value transformer; the shell handles the changing world.",
            "Returning a new outer list is not enough if the function still mutates nested objects shared with the caller.",
          ),
          section(
            "Use comprehensions as readable value builders",
            "A comprehension declares the output expression, source, and optional selection rule. Read it aloud as 'produce this for each item in that source when this condition holds.' It should create a new collection without side effects. If the expression or condition contains several domain rules, move them into a named helper or use a conventional loop.",
            "raw_topics = [\"  Python\", \"testing  \", \"\", \"APIs\"]\nclean_topics = [\n    topic.strip().casefold()\n    for topic in raw_topics\n    if topic.strip()\n]\nlength_by_topic = {topic: len(topic) for topic in clean_topics}\nprint(clean_topics)\nprint(length_by_topic)",
            [
              "Read expression, loop, and filter clauses in that order.",
              "Keep mutation and print out of the expression.",
              "Split separate conceptual stages into named comprehensions.",
            ],
            "Mental model: a comprehension describes the membership and value of a newly constructed collection.",
            "Repeating an expensive cleanup expression in both the result and filter clauses performs the work twice per item.",
          ),
          section(
            "Keep lazy production deterministic",
            "A generator can remain effect-light when its output depends only on the iterable passed to it. Local state persists between yields, so document what it summarizes. Avoid reading the clock, random state, or a globally changing collection during consumption; otherwise creating the generator twice with equal arguments may produce different streams.",
            "def running_totals(values):\n    total = 0\n    for value in values:\n        total += value\n        yield total\n\nfirst_pass = list(running_totals([4, -1, 6]))\nsecond_pass = list(running_totals([4, -1, 6]))\nassert first_pass == second_pass\nprint(first_pass)",
            [
              "State the meaning of local state after each yield.",
              "Treat the supplied source as read-only unless documented otherwise.",
              "Compare complete outputs from two fresh equal calls.",
            ],
            "Laziness changes when values are produced, not the requirement that equal inputs behave predictably.",
            "Reusing the same exhausted generator is not a repeatability test; create a fresh generator for each run.",
          ),
          section(
            "Use closures for stable configuration",
            "A closure is an inner function that retains names from the enclosing call after that call has returned. Capturing immutable configuration creates a predictable specialized function. Capture a normalized value rather than a caller-owned mutable object, and avoid counters or histories unless statefulness is an explicit requirement.",
            "def make_prefix_checker(prefix):\n    normalized_prefix = prefix.casefold()\n\n    def starts_with_prefix(text):\n        return text.casefold().startswith(normalized_prefix)\n\n    return starts_with_prefix\n\nis_error = make_prefix_checker(\"ERROR:\")\nassert is_error(\"error: disk full\") is True\nassert is_error(\"warning: disk slow\") is False",
            [
              "List every captured name and whether it can change.",
              "Normalize and freeze configuration at factory time.",
              "Call the returned function twice with equal input and compare results.",
            ],
            "Mental model: a closure packages a rule together with a small, stable environment.",
            "Capturing a mutable configuration dictionary means later caller edits can silently change the returned function's behaviour.",
          ),
        ],
        runbook: [
          runStep("1. Inventory effects", "Mark input, output, files, time, randomness, network use, globals, and mutation.", "A boundary-versus-pure-core diagram."),
          runStep("2. Make dependencies explicit", "Pass environmental facts and configuration through parameters instead of reading hidden state.", "A core whose result is determined by its arguments."),
          runStep("3. Construct new values", "Use clear comprehensions, tuples, or yields without modifying caller-owned objects.", "Result data plus unchanged input snapshots."),
          runStep("4. Freeze configuration", "Let closures capture normalized immutable values and document any deliberate state.", "Independent configured functions with named captured values."),
          runStep("5. Prove repeatability", "Run fresh calls with equal inputs and compare values, streams, and source snapshots.", "Evidence that order, history, and environment do not alter the core."),
        ],
      },

      py11: {
        title: "Divide and Conquer",
        subtitle: "Use structural promises and invariants to discard large parts of a problem safely.",
        objectives: [
          "Define binary-search boundaries without off-by-one errors.",
          "Exploit monotone and bitonic structure.",
          "Connect algorithm choice to time complexity.",
        ],
        tutorial: [
          section(
            "Divide a problem without losing the answer",
            "Divide and conquer splits a problem into smaller independent regions, solves those regions, and combines their answers. The invariant states what remains true about the current region. For finding a maximum, the maximum of the whole sequence must be the larger maximum of its two non-empty halves, so neither half is discarded without contributing evidence.",
            "def maximum_between(values, start, stop):\n    # Region uses half-open bounds: start <= index < stop.\n    if stop - start == 1:\n        return values[start]\n    middle = (start + stop) // 2\n    left_maximum = maximum_between(values, start, middle)\n    right_maximum = maximum_between(values, middle, stop)\n    return max(left_maximum, right_maximum)\n\nscores = [18, 41, 7, 29, 36]\nprint(maximum_between(scores, 0, len(scores)))",
            [
              "State what the current region contains and excludes.",
              "Stop at a region whose answer is direct.",
              "Explain how subanswers combine into the parent answer.",
            ],
            "Mental model: every recursive frame owns one region, delegates smaller regions, and combines their evidence.",
            "Splitting an empty region indefinitely means the base case and initial domain do not agree; validate non-empty input or define an empty result.",
          ),
          section(
            "Choose one interval convention and keep it",
            "An inclusive region [start, end] contains both boundaries; a half-open region [start, stop) includes start and excludes stop. Half-open regions make their size stop - start and allow an empty region when both bounds match. Whichever convention you choose must determine initialization, base cases, slice boundaries, and updates consistently.",
            "def split_region(start, stop):\n    # Half-open region [start, stop).\n    middle = start + (stop - start) // 2\n    left = (start, middle)\n    right = (middle, stop)\n    return left, right\n\nprint(split_region(3, 10))   # sizes 3 and 4\nprint(split_region(5, 5))    # two empty regions",
            [
              "Write the convention beside the bounds.",
              "Calculate region size from that convention.",
              "Test empty, one-element, two-element, odd, and even regions.",
            ],
            "Mental model: bounds define a mathematical set of candidate indexes, not vague pointers near the answer.",
            "Mixing an inclusive initial end with a half-open stop condition can skip the final element or index beyond the list.",
          ),
          section(
            "Search a monotone predicate, not arbitrary data",
            "Halving is safe when the observations have a one-way structure. A monotone predicate is false for an initial region and true from some boundary onward, or the reverse. The goal is to find that boundary while preserving a candidate interval. First prove that the predicate cannot switch back; without that promise, one middle observation does not justify discarding a side.",
            "# Find the smallest batch whose measured duration reaches a limit.\ndef first_slow_batch(durations, limit):\n    start, stop = 0, len(durations)\n    while start < stop:\n        middle = (start + stop) // 2\n        if durations[middle] < limit:\n            start = middle + 1\n        else:\n            stop = middle\n    return start\n\nmeasurements = [12, 18, 27, 35, 49, 63]\nprint(first_slow_batch(measurements, 40))",
            [
              "State and verify the one-way structural promise.",
              "Define the answer when every item is false or every item is true.",
              "Explain whether the middle index remains a possible boundary in each branch.",
            ],
            "Mental model: a monotone predicate turns many values into a single false-to-true frontier.",
            "Stopping at the first true midpoint finds a true item, not necessarily the earliest true item; retain it as a candidate and continue left.",
          ),
          section(
            "Account for divide, solve, and combine costs",
            "Complexity depends on the number of subproblems, their size, and the work used to combine answers. Repeated halving along one path gives logarithmic depth. Visiting both halves can still touch every element. Copying slices adds work and memory, so passing index bounds often preserves the intended complexity more faithfully.",
            "competitors = 1_024\nrounds = 0\nremaining = competitors\nwhile remaining > 1:\n    remaining = (remaining + 1) // 2\n    rounds += 1\nprint(rounds)  # ten rounds of halving\n\n# A tournament has logarithmic rounds but still many total matches.",
            [
              "Name n and describe subproblem sizes after one level.",
              "Separate maximum depth from total work across all branches.",
              "Include slicing, combining, and helper costs in the budget.",
            ],
            "Mental model: depth measures the longest dependency chain; total work measures every node of the computation tree.",
            "Calling an O(n) helper at each supposedly logarithmic search step can turn a fast-looking design into linear or worse work.",
          ),
        ],
        runbook: [
          runStep("1. Confirm the promise", "State whether input is sorted, monotone, recursively splittable, or otherwise structured.", "A counterexample showing why the algorithm needs that promise."),
          runStep("2. Define regions", "Choose inclusive or half-open bounds and write exactly which indexes they contain.", "Initialization, size formula, and invariant using one convention."),
          runStep("3. Justify reduction", "Explain what a middle observation or subanswer proves about each region.", "A proof for every discarded or combined half."),
          runStep("4. Prove shrinkage", "Show that every non-base path produces strictly smaller regions.", "Traces for empty, one-, two-, odd-, and even-sized regions."),
          runStep("5. Budget the tree", "Count subproblems, depth, combination work, copying, and extra storage.", "Time and space complexity tied to the actual implementation."),
        ],
      },
    },
  };
})();
