(() => {
  "use strict";

  window.LEARNING_TOOLBOX = {
    py01: [
      {
        kind: "Built-in · conversion",
        syntax: "int(text)",
        description: "Explicit type conversion—often casually called casting—parses valid whole-number text and creates an integer without changing the original string.",
        useWhen: "A supplied value represents an exact whole count that must participate in arithmetic.",
        result: "An int; invalid whole-number text raises ValueError.",
        caution: "int(\"3.5\") fails, while int(3.5) truncates toward zero rather than rounding. Keep identifiers such as \"007\" as text.",
        example: "raw_tickets = \" 18 \"\nticket_count = int(raw_tickets)\nprint(ticket_count + 2)",
      },
      {
        kind: "Built-in · conversion",
        syntax: "float(text_or_number)",
        description: "Creates a floating-point value from valid decimal text or another compatible number.",
        useWhen: "The domain permits fractional measurements, rates, or ratios.",
        result: "A float, normally stored as a binary approximation.",
        caution: "Malformed text raises ValueError, and many decimal fractions cannot be represented exactly as floats.",
        example: "raw_depth = \"3.75\"\ndepth_metres = float(raw_depth)\nprint(depth_metres * 2)",
      },
      {
        kind: "Built-in · conversion",
        syntax: "str(value)",
        description: "Creates a human-readable text representation of a value.",
        useWhen: "Text must be assembled deliberately outside print or an f-string.",
        result: "A str suitable for concatenation, storage, or display.",
        caution: "After conversion, arithmetic is no longer numeric. print and f-strings already format values, so str is not always necessary.",
        example: "crate_count = 6\nlabel = str(crate_count) + \" crates\"\nprint(label)",
      },
      {
        kind: "Built-in · conversion",
        syntax: "bool(value)",
        description: "Applies Python's truth-value rules rather than parsing words such as true or false.",
        useWhen: "A program must ask whether a value is empty, zero, None, or otherwise truthy.",
        result: "True or False.",
        caution: "bool(\"False\") and bool(\"0\") are both True because both strings are non-empty. Parse textual flags explicitly.",
        example: "raw_flag = \"False\"\nprint(bool(raw_flag))\nprint(raw_flag.casefold() == \"true\")",
      },
    ],

    py02: [
      {
        kind: "Built-in · numeric",
        syntax: "round(number, ndigits=None)",
        description: "Rounds to the nearest requested power of ten; exact ties use the even candidate.",
        useWhen: "The numeric contract explicitly requests a rounded value.",
        result: "For built-in int and float values, omitting ndigits returns an int; with ndigits, an int stays int and a float stays float.",
        caution: "Floats are approximate, early rounding loses information, and round(value, 2) does not guarantee two visible decimal digits.",
        example: "print(round(2.5), round(3.5))\nmeasurement = 8 / 3\nprint(round(measurement, 2))",
      },
      {
        kind: "Language · formatting",
        syntax: "f\"{value:.2f}\"",
        description: "Formats a number as text with exactly two visible digits after the decimal point.",
        useWhen: "The output contract specifies display precision or trailing zeroes.",
        result: "A str, not a rounded numeric value for later arithmetic.",
        caution: "Formatting changes representation into text. Keep a separate numeric value when more calculation follows.",
        example: "measurement = 7 / 4\nnumeric_value = round(measurement, 2)\ndisplay_value = f\"{measurement:.2f}\"\nprint(type(numeric_value).__name__)\nprint(type(display_value).__name__)",
      },
      {
        kind: "Standard library · math",
        syntax: "math.isclose(a, b, rel_tol=..., abs_tol=...)",
        description: "Compares floating-point values using a deliberate relative or absolute tolerance.",
        useWhen: "Two calculated measurements should be considered equivalent within a stated tolerance.",
        result: "A bool.",
        caution: "Choose tolerances from the domain. Near zero, an explicit abs_tol is often needed; exact integers should usually be compared directly.",
        importCode: "import math",
        example: "observed = 0.1 + 0.2\nexpected = 0.3\nprint(math.isclose(observed, expected, rel_tol=1e-9, abs_tol=0.0))",
      },
      {
        kind: "Language · imports",
        syntax: "import module  |  from module import name",
        description: "An import binds a module namespace or selected names. Built-ins need no import; standard-library modules ship with Python; third-party packages require separate installation.",
        useWhen: "A documented tool is not a built-in and is available in the exercise runtime.",
        result: "One or more names become available in the current namespace.",
        caution: "Import does not install packages. Avoid wildcard imports, local files that shadow library names, and assuming that from-module imports also bind the module name.",
        importCode: "import textwrap",
        example: "note = \"Calibration completed without warnings\"\npreview = textwrap.shorten(note, width=24, placeholder=\"...\")\nprint(preview)",
      },
    ],

    py03: [
      {
        kind: "Built-in · iterable",
        syntax: "range(start, stop, step=1)",
        description: "Represents a half-open arithmetic progression whose stop value is excluded.",
        useWhen: "A loop has a known count or a numeric progression with a fixed step.",
        result: "A reusable range object that produces integers on demand.",
        caution: "The stop is excluded, step cannot be zero, and a negative step needs compatible start and stop values.",
        example: "for checkpoint in range(2, 9, 2):\n    print(checkpoint)",
      },
      {
        kind: "Built-in · iterator",
        syntax: "enumerate(iterable, start=0)",
        description: "Pairs each item with a counter without maintaining a separate counter variable.",
        useWhen: "Both an item's position and value are needed during traversal.",
        result: "A one-pass iterator of (counter, item) tuples.",
        caution: "The start argument changes the displayed counter; it does not alter the source collection's real indexes.",
        example: "statuses = [\"queued\", \"running\", \"done\"]\nfor position, status in enumerate(statuses, start=1):\n    print(position, status)",
      },
      {
        kind: "Language · control flow",
        syntax: "break  |  continue",
        description: "break exits the nearest loop; continue skips the remainder of the current iteration.",
        useWhen: "A decisive answer permits early stopping or a known item should be ignored.",
        result: "Control moves to the statement after the loop or to its next iteration.",
        caution: "Only the nearest loop is affected. Preserve any state that code after the loop needs.",
        example: "attempts = [\"\", \"busy\", \"ready\", \"later\"]\nfor state in attempts:\n    if not state:\n        continue\n    if state == \"ready\":\n        print(\"found\")\n        break",
      },
    ],

    py04: [
      {
        kind: "Language · functions",
        syntax: "def name(parameters): ... return value",
        description: "Defines a callable contract with explicit inputs and a value returned to its caller.",
        useWhen: "A transformation has a meaningful name, independent tests, or more than one caller.",
        result: "The explicit returned value; falling off the function body returns None.",
        caution: "print displays data but returns None. Check every branch for a stable return type and avoid hidden global dependencies.",
        example: "def make_status_label(code, state):\n    return f\"{code}: {state}\"\n\nlabel = make_status_label(\"A7\", \"ready\")\nprint(label)",
      },
      {
        kind: "Built-in · type check",
        syntax: "isinstance(value, accepted_types)",
        description: "Checks whether a value conforms to one type or a tuple of accepted types, including subclasses.",
        useWhen: "A function contract deliberately supports several related runtime types.",
        result: "A bool.",
        caution: "bool is a subclass of int. Prefer checking the capability or domain rule when exact concrete type is not important.",
        example: "def double_measurement(value):\n    numeric = isinstance(value, (int, float))\n    if not numeric or isinstance(value, bool):\n        return None\n    return value * 2\n\nprint(double_measurement(4.5))",
      },
      {
        kind: "Built-in · discovery",
        syntax: "help(callable)",
        description: "Displays documentation for a function, type, module, or other documented object.",
        useWhen: "Exploring an unfamiliar tool in a scratch run before integrating it.",
        result: "Writes help text to standard output and returns None.",
        caution: "Help output will break exact-output tests. Use it during investigation, then remove it and confirm details in official documentation.",
        example: "help(round)",
      },
      {
        kind: "Standard library · introspection",
        syntax: "inspect.signature(callable)",
        description: "Returns a structured view of a callable's parameters, defaults, and parameter kinds.",
        useWhen: "Learning how an unfamiliar callable must be invoked or documenting a function contract.",
        result: "An inspect.Signature object.",
        caution: "Some extension or dynamically generated callables do not expose a signature. Documented behavior remains more important than the shape alone.",
        importCode: "import inspect",
        example: "def scale(value, factor=1):\n    return value * factor\n\nprint(inspect.signature(scale))",
      },
    ],

    py05: [
      {
        kind: "String method · parsing",
        syntax: "text.split(separator, maxsplit=-1)",
        description: "Parses one string into a list of fields around a delimiter.",
        useWhen: "External text encodes several fields with a known separator.",
        result: "A new list of strings; the original text remains unchanged.",
        caution: "An explicit separator preserves empty fields, while split() without one collapses runs of whitespace. Validate the resulting shape before unpacking.",
        example: "record = \"green;42;open\"\nfields = record.split(\";\")\ncolour, count_text, state = fields\nprint(colour, state)",
      },
      {
        kind: "String method · assembly",
        syntax: "separator.join(strings)",
        description: "Constructs one string by placing the separator between supplied string pieces.",
        useWhen: "Structured text pieces must be assembled with exact, consistent punctuation.",
        result: "A new str.",
        caution: "Every item must already be a string. Convert deliberate numeric fields before joining rather than repeatedly concatenating.",
        example: "stages = [\"draft\", \"reviewed\", \"archived\"]\ntimeline = \" -> \".join(stages)\nprint(timeline)",
      },
      {
        kind: "Language · sequences",
        syntax: "sequence[start:stop:step]",
        description: "Selects a half-open region or stride from a string, tuple, list, or another sliceable sequence.",
        useWhen: "Positions or boundaries are clearer than an element-by-element loop.",
        result: "A new sliced value, normally of the source sequence type.",
        caution: "The stop is excluded, step cannot be zero, and out-of-range slice bounds usually return a shorter value instead of raising an error.",
        example: "letters = \"ABCDEFGHI\"\nselected = letters[1:7:2]\nprint(selected)",
      },
      {
        kind: "String method · validation",
        syntax: "text.isdecimal()",
        description: "Checks whether a non-empty string consists entirely of decimal characters.",
        useWhen: "Textual digit content must be validated while its original representation remains intact.",
        result: "A bool.",
        caution: "Signs, decimal points, and surrounding spaces make it False. A digit-only identifier may still need to remain a string to preserve leading zeroes.",
        example: "route_code = \"007\"\nprint(route_code.isdecimal())\nprint(route_code)",
      },
    ],

    py06: [
      {
        kind: "List method · copying",
        syntax: "items.copy()",
        description: "Creates a shallow list copy so top-level edits do not change the original list.",
        useWhen: "A function or workflow needs an independent top-level working list.",
        result: "A new list containing references to the same element objects.",
        caution: "Nested mutable elements remain shared. Use an explicit reconstruction when ownership must extend into nested data.",
        example: "original = [\"draft\", \"review\"]\nworking = original.copy()\nworking.append(\"approved\")\nprint(original)\nprint(working)",
      },
      {
        kind: "List method · mutation",
        syntax: "items.append(value)",
        description: "Mutates a list by adding one value at its end.",
        useWhen: "The current code owns the list and deliberately grows it one item at a time.",
        result: "None; the change is visible in the list itself.",
        caution: "Do not assign the return value back to the list. append adds one object, so appending a list creates a nested list.",
        example: "tasks = [\"lint\"]\nreturned = tasks.append(\"test\")\nprint(tasks)\nprint(returned)",
      },
      {
        kind: "Built-in · ordering",
        syntax: "sorted(iterable, key=None, reverse=False)",
        description: "Consumes an iterable and returns a newly ordered list without modifying the source.",
        useWhen: "The caller needs ordered data while preserving the original collection.",
        result: "A new list.",
        caution: "list.sort() instead mutates a list and returns None. A key function must return comparable values consistently.",
        example: "labels = [\"gamma\", \"pi\", \"delta\"]\nordered = sorted(labels, key=len)\nprint(labels)\nprint(ordered)",
      },
    ],

    py07: [
      {
        kind: "Dictionary method · lookup",
        syntax: "mapping.get(key, default=None)",
        description: "Retrieves a value without raising KeyError when the key is absent.",
        useWhen: "A missing key has an explicit fallback meaning.",
        result: "The stored value or the supplied default.",
        caution: "get cannot distinguish an absent key from a present key whose value equals the default. Use key in mapping when that distinction matters.",
        example: "settings = {\"theme\": \"dark\"}\npage_size = settings.get(\"page_size\", 25)\nprint(page_size)",
      },
      {
        kind: "Dictionary view · iteration",
        syntax: "mapping.items()",
        description: "Exposes dynamic (key, value) pairs for traversal and unpacking.",
        useWhen: "Both identity and associated data are needed together.",
        result: "A reusable dict_items view tied to the dictionary.",
        caution: "Do not change dictionary size while iterating; it can raise RuntimeError or produce incomplete traversal. Collect planned additions or removals and apply them afterward.",
        example: "limits = {\"warning\": 70, \"critical\": 90}\nfor name, threshold in limits.items():\n    print(name, threshold)",
      },
      {
        kind: "Set operators · membership",
        syntax: "left | right  |  left & right  |  left - right  |  left ^ right",
        description: "Creates union, intersection, difference, or symmetric-difference sets.",
        useWhen: "The domain asks about membership overlap rather than position or duplicates.",
        result: "A new set.",
        caution: "Set elements must be hashable, duplicates disappear, and iteration order should not be part of the output contract.",
        example: "morning = {\"api\", \"docs\", \"tests\"}\nevening = {\"tests\", \"deploy\"}\nprint(morning & evening)\nprint(morning - evening)",
      },
      {
        kind: "Standard library · interface",
        syntax: "isinstance(value, Mapping)",
        description: "Checks whether an object supports the read-only mapping interface rather than requiring an exact dict.",
        useWhen: "A function accepts any dictionary-like input with keys and values.",
        result: "A bool.",
        caution: "Mapping does not promise mutability. Use MutableMapping only when the contract genuinely changes the supplied object.",
        importCode: "from collections.abc import Mapping",
        example: "settings = {\"theme\": \"dark\"}\nprint(isinstance(settings, Mapping))",
      },
    ],

    py08: [
      {
        kind: "Pattern · recursion",
        syntax: "base case -> smaller recursive call -> combine",
        description: "Answers the smallest input directly and expresses every larger input through a strictly smaller version.",
        useWhen: "The problem has a natural nested or shrinking structure whose returned results can be combined.",
        result: "One returned value assembled while calls unwind.",
        caution: "Every path needs a reachable base case and measurable progress. Printing calls is not a substitute for returning and combining their answers.",
        example: "def countdown_label(level):\n    if level == 0:\n        return \"launch\"\n    return f\"{level} > \" + countdown_label(level - 1)\n\nprint(countdown_label(3))",
      },
      {
        kind: "Standard library · decorator",
        syntax: "@lru_cache(maxsize=...)",
        description: "Caches results by a key built from hashable call arguments, so repeated calls with the same argument pattern can reuse a deterministic result.",
        useWhen: "A pure function repeatedly receives the same hashable arguments and its work is meaningfully expensive.",
        result: "A wrapped callable with the same returned values plus cache inspection methods.",
        caution: "Mutable arguments are unhashable, side effects must not be cached, and an unlimited cache can retain memory indefinitely.",
        importCode: "from functools import lru_cache",
        example: "@lru_cache(maxsize=32)\ndef normalized_label(raw_label):\n    return raw_label.strip().casefold()\n\nprint(normalized_label(\"  READY \"))\nprint(normalized_label.cache_info())",
      },
      {
        kind: "Standard library · diagnostic",
        syntax: "sys.getrecursionlimit()",
        description: "Reports the interpreter's maximum Python call-stack depth setting.",
        useWhen: "Diagnosing why a structurally correct recursive design fails only for deep inputs.",
        result: "An int.",
        caution: "Raising the limit is rarely the right first fix and can crash the process. Remove repeated work or choose iteration when depth naturally scales with large input.",
        importCode: "import sys",
        example: "limit = sys.getrecursionlimit()\nprint(limit)",
      },
    ],

    py09: [
      {
        kind: "Built-in · lazy transform",
        syntax: "map(function, iterable)",
        description: "Applies one function lazily to each source item.",
        useWhen: "Every item undergoes the same single-purpose transformation.",
        result: "A one-pass map iterator.",
        caution: "Work begins during consumption, not construction. A mutating callback such as list.append returns None and therefore maps to None values.",
        example: "raw_labels = [\"  alpha\", \"beta  \", \" gamma \"]\ncleaned = map(str.strip, raw_labels)\nprint(list(cleaned))",
      },
      {
        kind: "Built-in · lazy selection",
        syntax: "filter(predicate, iterable)",
        description: "Lazily retains items for which a predicate returns a truthy value.",
        useWhen: "Selection is one clear yes-or-no question per item.",
        result: "A one-pass filter iterator.",
        caution: "The predicate should not transform items or mutate external state. Materializing it consumes the iterator.",
        example: "states = [\"ok\", \"\", \"retry\", \"ready\"]\nnonempty = filter(bool, states)\nprint(list(nonempty))",
      },
      {
        kind: "Standard library · reduction",
        syntax: "reduce(function, iterable, initializer)",
        description: "Combines an accumulator and each item into one final accumulator.",
        useWhen: "The answer-so-far has a stable meaning and no clearer built-in such as sum, min, max, any, all, or join fits.",
        result: "One accumulated value.",
        caution: "The initializer defines empty-input behavior and must match the accumulator type. reduce is not a built-in and must be imported.",
        importCode: "from functools import reduce",
        example: "def add_label_length(total, label):\n    return total + len(label)\n\nlabels = [\"oak\", \"pine\", \"elm\"]\nprint(reduce(add_label_length, labels, 0))",
      },
      {
        kind: "Standard library · iterator",
        syntax: "islice(iterable, stop)",
        description: "Consumes only a bounded slice of an iterator without building the entire source first.",
        useWhen: "A lazy or very large stream needs a preview or a finite window.",
        result: "A one-pass islice iterator.",
        caution: "When the source is an iterator, consumed items cannot be replayed from that iterator. Negative indexes are unsupported.",
        importCode: "from itertools import islice",
        example: "stream = (name.upper() for name in [\"one\", \"two\", \"three\", \"four\"])\npreview = list(islice(stream, 2))\nprint(preview)\nprint(list(stream))",
      },
    ],

    py10: [
      {
        kind: "Language · comprehension",
        syntax: "[transform(item) for item in source if predicate(item)]",
        description: "Constructs a new list by describing its source, optional selection, and output value.",
        useWhen: "A short pure transformation creates a concrete collection immediately.",
        result: "A new list.",
        caution: "Do not place print, append, or other side effects inside the expression. Use named stages when several domain rules would make it dense.",
        example: "raw_labels = [\"  Alpha \", \"\", \" beta\"]\ncleaned = [\n    label.strip().casefold()\n    for label in raw_labels\n    if label.strip()\n]\nprint(cleaned)",
      },
      {
        kind: "Language · generator",
        syntax: "(transform(item) for item in source if predicate(item))",
        description: "Describes a lazy one-pass transformation without constructing a complete result list.",
        useWhen: "A consumer can process items forward once or stop early.",
        result: "A generator iterator.",
        caution: "Creation does not run the work, inspection can consume values, and a second traversal requires a fresh generator.",
        example: "raw_lines = [\" first \", \" \", \"second\", \" third \"]\ncleaned = (line.strip() for line in raw_lines if line.strip())\nprint(next(cleaned))\nprint(list(cleaned))",
      },
      {
        kind: "Standard library · callable",
        syntax: "partial(function, /, *fixed_args, **fixed_kwargs)",
        description: "Creates a new callable with selected arguments preconfigured.",
        useWhen: "Several callers share one function and a small stable configuration.",
        result: "A functools.partial callable.",
        caution: "Captured mutable objects can still change later. Prefer explicit names and immutable configuration so the specialized callable remains understandable.",
        importCode: "from functools import partial",
        example: "def decorate(prefix, text):\n    return prefix + text\n\nwarning_label = partial(decorate, \"WARN: \")\nprint(warning_label(\"disk almost full\"))",
      },
      {
        kind: "Built-in · conversion",
        syntax: "tuple(iterable)",
        description: "Materializes an iterable as a fixed outer sequence that cannot be resized or reassigned by index.",
        useWhen: "A stable snapshot or read-only positional result is part of the function contract.",
        result: "A tuple.",
        caution: "Tuple immutability is shallow: nested lists or dictionaries remain mutable and shared.",
        example: "mutable_stages = [\"build\", \"test\"]\nsnapshot = tuple(mutable_stages)\nmutable_stages.append(\"deploy\")\nprint(snapshot)\nprint(mutable_stages)",
      },
    ],

    py11: [
      {
        kind: "Pattern · index ranges",
        syntax: "middle = (low + high) // 2",
        description: "Represents a candidate region with integer boundaries instead of copying sublists.",
        useWhen: "An algorithm repeatedly inspects a midpoint and discards a provably irrelevant region.",
        result: "A midpoint index used to derive a smaller pair of candidate bounds.",
        caution: "Document whether high is inclusive or exclusive and keep that convention everywhere. Slicing can hide extra copying and offset mistakes.",
        example: "def middle_entry(values, low, high):\n    if low > high:\n        return None\n    middle = (low + high) // 2\n    return middle, values[middle]\n\nprint(middle_entry([\"a\", \"b\", \"c\", \"d\"], 0, 3))",
      },
      {
        kind: "Standard library · mathematics",
        syntax: "math.log2(value)",
        description: "Returns the base-two logarithm, useful for estimating how many repeated halvings reduce a positive size to one.",
        useWhen: "Explaining expected divide-and-conquer depth or comparing growth rates.",
        result: "A float.",
        caution: "The input must be positive, and a complexity estimate does not prove that an implementation actually discards half on every step.",
        importCode: "import math",
        example: "item_count = 256\nestimated_levels = math.ceil(math.log2(item_count))\nprint(estimated_levels)",
      },
      {
        kind: "Standard library · measurement",
        syntax: "repeat(callable, repeat=..., number=...)",
        description: "Runs a callable in repeated timing batches and returns the measured durations.",
        useWhen: "Checking whether runtime growth matches a reasoned complexity model after correctness is established.",
        result: "A list of elapsed times in seconds.",
        caution: "Microbenchmarks are noisy. Compare equivalent work, use several input sizes, avoid I/O, and report a statistic rather than one run.",
        importCode: "from timeit import repeat",
        example: "samples = repeat(\n    lambda: tuple(range(100)),\n    repeat=3,\n    number=500,\n)\nprint(min(samples))",
      },
    ],
  };
})();
